version: '3.7'

services:
  fe:
    container_name: shopp_fe
    build: 
      context: .
      dockerfile: Dockerfile
    command:
      - sh
      - -c
      - "npm start"
    ports:
      - 8080:3000
    networks:
      - shopp
    restart: always

networks:
  shopp:
    driver: bridge