version: '3.7'

services:
  fe:
    container_name: shopp_fe
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
    depends_on:
      - be
    networks:
      - shopp
    restart: always

networks:
  shopp:
    driver: bridge