version: '3.7'

services:
  fe:
    container_name: shopp_fe
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:80
    networks:
      - shopp
    restart: always

networks:
  shopp:
    driver: bridge