export const HUYEN_DATA = [
  {
    name: "Điện Biên",
    code: "100",
    parent_code: "11",
    path_with_type: "Huyện Điện Biên, Tỉnh Điện Biên",
  },
  {
    name: "Điện Biên Đông",
    code: "101",
    parent_code: "11",
    path_with_type: "Huyện Điện Biên Đông, Tỉnh Điện Biên",
  },
  {
    name: "Mường Ảng",
    code: "102",
    parent_code: "11",
    path_with_type: "Huyện Mường Ảng, Tỉnh Điện Biên",
  },
  {
    name: "Nậm Pồ",
    code: "103",
    parent_code: "11",
    path_with_type: "Huyện Nậm Pồ, Tỉnh Điện Biên",
  },
  {
    name: "Lai Châu",
    code: "105",
    parent_code: "12",
    path_with_type: "Thành phố Lai Châu, Tỉnh Lai Châu",
  },
  {
    name: "Tam Đường",
    code: "106",
    parent_code: "12",
    path_with_type: "Huyện Tam Đường, Tỉnh Lai Châu",
  },
  {
    name: "Mường Tè",
    code: "107",
    parent_code: "12",
    path_with_type: "Huyện Mường Tè, Tỉnh Lai Châu",
  },
  {
    name: "Sìn Hồ",
    code: "108",
    parent_code: "12",
    path_with_type: "Huyện Sìn Hồ, Tỉnh Lai Châu",
  },
  {
    name: "Phong Thổ",
    code: "109",
    parent_code: "12",
    path_with_type: "Huyện Phong Thổ, Tỉnh Lai Châu",
  },
  {
    name: "Than Uyên",
    code: "110",
    parent_code: "12",
    path_with_type: "Huyện Than Uyên, Tỉnh Lai Châu",
  },
  {
    name: "Tân Uyên",
    code: "111",
    parent_code: "12",
    path_with_type: "Huyện Tân Uyên, Tỉnh Lai Châu",
  },
  {
    name: "Nậm Nhùn",
    code: "112",
    parent_code: "12",
    path_with_type: "Huyện Nậm Nhùn, Tỉnh Lai Châu",
  },
  {
    name: "Sơn La",
    code: "116",
    parent_code: "14",
    path_with_type: "Thành phố Sơn La, Tỉnh Sơn La",
  },
  {
    name: "Quỳnh Nhai",
    code: "118",
    parent_code: "14",
    path_with_type: "Huyện Quỳnh Nhai, Tỉnh Sơn La",
  },
  {
    name: "Thuận Châu",
    code: "119",
    parent_code: "14",
    path_with_type: "Huyện Thuận Châu, Tỉnh Sơn La",
  },
  {
    name: "Mường La",
    code: "120",
    parent_code: "14",
    path_with_type: "Huyện Mường La, Tỉnh Sơn La",
  },
  {
    name: "Bắc Yên",
    code: "121",
    parent_code: "14",
    path_with_type: "Huyện Bắc Yên, Tỉnh Sơn La",
  },
  {
    name: "Phù Yên",
    code: "122",
    parent_code: "14",
    path_with_type: "Huyện Phù Yên, Tỉnh Sơn La",
  },
  {
    name: "Mộc Châu",
    code: "123",
    parent_code: "14",
    path_with_type: "Huyện Mộc Châu, Tỉnh Sơn La",
  },
  {
    name: "Yên Châu",
    code: "124",
    parent_code: "14",
    path_with_type: "Huyện Yên Châu, Tỉnh Sơn La",
  },
  {
    name: "Mai Sơn",
    code: "125",
    parent_code: "14",
    path_with_type: "Huyện Mai Sơn, Tỉnh Sơn La",
  },
  {
    name: "Sông Mã",
    code: "126",
    parent_code: "14",
    path_with_type: "Huyện Sông Mã, Tỉnh Sơn La",
  },
  {
    name: "Sốp Cộp",
    code: "127",
    parent_code: "14",
    path_with_type: "Huyện Sốp Cộp, Tỉnh Sơn La",
  },
  {
    name: "Vân Hồ",
    code: "128",
    parent_code: "14",
    path_with_type: "Huyện Vân Hồ, Tỉnh Sơn La",
  },
  {
    name: "Yên Bái",
    code: "132",
    parent_code: "15",
    path_with_type: "Thành phố Yên Bái, Tỉnh Yên Bái",
  },
  {
    name: "Nghĩa Lộ",
    code: "133",
    parent_code: "15",
    path_with_type: "Thị xã Nghĩa Lộ, Tỉnh Yên Bái",
  },
  {
    name: "Lục Yên",
    code: "135",
    parent_code: "15",
    path_with_type: "Huyện Lục Yên, Tỉnh Yên Bái",
  },
  {
    name: "Văn Yên",
    code: "136",
    parent_code: "15",
    path_with_type: "Huyện Văn Yên, Tỉnh Yên Bái",
  },
  {
    name: "Mù Căng Chải",
    code: "137",
    parent_code: "15",
    path_with_type: "Huyện Mù Căng Chải, Tỉnh Yên Bái",
  },
  {
    name: "Trấn Yên",
    code: "138",
    parent_code: "15",
    path_with_type: "Huyện Trấn Yên, Tỉnh Yên Bái",
  },
  {
    name: "Trạm Tấu",
    code: "139",
    parent_code: "15",
    path_with_type: "Huyện Trạm Tấu, Tỉnh Yên Bái",
  },
  {
    name: "Văn Chấn",
    code: "140",
    parent_code: "15",
    path_with_type: "Huyện Văn Chấn, Tỉnh Yên Bái",
  },
  {
    name: "Yên Bình",
    code: "141",
    parent_code: "15",
    path_with_type: "Huyện Yên Bình, Tỉnh Yên Bái",
  },
  {
    name: "Hòa Bình",
    code: "148",
    parent_code: "17",
    path_with_type: "Thành phố Hòa Bình, Tỉnh Hoà Bình",
  },
  {
    name: "Đà Bắc",
    code: "150",
    parent_code: "17",
    path_with_type: "Huyện Đà Bắc, Tỉnh Hoà Bình",
  },
  {
    name: "Kỳ Sơn",
    code: "151",
    parent_code: "17",
    path_with_type: "Huyện Kỳ Sơn, Tỉnh Hoà Bình",
  },
  {
    name: "Lương Sơn",
    code: "152",
    parent_code: "17",
    path_with_type: "Huyện Lương Sơn, Tỉnh Hoà Bình",
  },
  {
    name: "Kim Bôi",
    code: "153",
    parent_code: "17",
    path_with_type: "Huyện Kim Bôi, Tỉnh Hoà Bình",
  },
  {
    name: "Cao Phong",
    code: "154",
    parent_code: "17",
    path_with_type: "Huyện Cao Phong, Tỉnh Hoà Bình",
  },
  {
    name: "Tân Lạc",
    code: "155",
    parent_code: "17",
    path_with_type: "Huyện Tân Lạc, Tỉnh Hoà Bình",
  },
  {
    name: "Mai Châu",
    code: "156",
    parent_code: "17",
    path_with_type: "Huyện Mai Châu, Tỉnh Hoà Bình",
  },
  {
    name: "Lạc Sơn",
    code: "157",
    parent_code: "17",
    path_with_type: "Huyện Lạc Sơn, Tỉnh Hoà Bình",
  },
  {
    name: "Yên Thủy",
    code: "158",
    parent_code: "17",
    path_with_type: "Huyện Yên Thủy, Tỉnh Hoà Bình",
  },
  {
    name: "Lạc Thủy",
    code: "159",
    parent_code: "17",
    path_with_type: "Huyện Lạc Thủy, Tỉnh Hoà Bình",
  },
  {
    name: "Thái Nguyên",
    code: "164",
    parent_code: "19",
    path_with_type: "Thành phố Thái Nguyên, Tỉnh Thái Nguyên",
  },
  {
    name: "Sông Công",
    code: "165",
    parent_code: "19",
    path_with_type: "Thành phố Sông Công, Tỉnh Thái Nguyên",
  },
  {
    name: "Định Hóa",
    code: "167",
    parent_code: "19",
    path_with_type: "Huyện Định Hóa, Tỉnh Thái Nguyên",
  },
  {
    name: "Phú Lương",
    code: "168",
    parent_code: "19",
    path_with_type: "Huyện Phú Lương, Tỉnh Thái Nguyên",
  },
  {
    name: "Đồng Hỷ",
    code: "169",
    parent_code: "19",
    path_with_type: "Huyện Đồng Hỷ, Tỉnh Thái Nguyên",
  },
  {
    name: "Võ Nhai",
    code: "170",
    parent_code: "19",
    path_with_type: "Huyện Võ Nhai, Tỉnh Thái Nguyên",
  },
  {
    name: "Đại Từ",
    code: "171",
    parent_code: "19",
    path_with_type: "Huyện Đại Từ, Tỉnh Thái Nguyên",
  },
  {
    name: "Phổ Yên",
    code: "172",
    parent_code: "19",
    path_with_type: "Thị xã Phổ Yên, Tỉnh Thái Nguyên",
  },
  {
    name: "Phú Bình",
    code: "173",
    parent_code: "19",
    path_with_type: "Huyện Phú Bình, Tỉnh Thái Nguyên",
  },
  {
    name: "Lạng Sơn",
    code: "178",
    parent_code: "20",
    path_with_type: "Thành phố Lạng Sơn, Tỉnh Lạng Sơn",
  },
  {
    name: "Tràng Định",
    code: "180",
    parent_code: "20",
    path_with_type: "Huyện Tràng Định, Tỉnh Lạng Sơn",
  },
  {
    name: "Bình Gia",
    code: "181",
    parent_code: "20",
    path_with_type: "Huyện Bình Gia, Tỉnh Lạng Sơn",
  },
  {
    name: "Văn Lãng",
    code: "182",
    parent_code: "20",
    path_with_type: "Huyện Văn Lãng, Tỉnh Lạng Sơn",
  },
  {
    name: "Cao Lộc",
    code: "183",
    parent_code: "20",
    path_with_type: "Huyện Cao Lộc, Tỉnh Lạng Sơn",
  },
  {
    name: "Văn Quan",
    code: "184",
    parent_code: "20",
    path_with_type: "Huyện Văn Quan, Tỉnh Lạng Sơn",
  },
  {
    name: "Bắc Sơn",
    code: "185",
    parent_code: "20",
    path_with_type: "Huyện Bắc Sơn, Tỉnh Lạng Sơn",
  },
  {
    name: "Hữu Lũng",
    code: "186",
    parent_code: "20",
    path_with_type: "Huyện Hữu Lũng, Tỉnh Lạng Sơn",
  },
  {
    name: "Chi Lăng",
    code: "187",
    parent_code: "20",
    path_with_type: "Huyện Chi Lăng, Tỉnh Lạng Sơn",
  },
  {
    name: "Lộc Bình",
    code: "188",
    parent_code: "20",
    path_with_type: "Huyện Lộc Bình, Tỉnh Lạng Sơn",
  },
  {
    name: "Đình Lập",
    code: "189",
    parent_code: "20",
    path_with_type: "Huyện Đình Lập, Tỉnh Lạng Sơn",
  },
  {
    name: "Hạ Long",
    code: "193",
    parent_code: "22",
    path_with_type: "Thành phố Hạ Long, Tỉnh Quảng Ninh",
  },
  {
    name: "Móng Cái",
    code: "194",
    parent_code: "22",
    path_with_type: "Thành phố Móng Cái, Tỉnh Quảng Ninh",
  },
  {
    name: "Cẩm Phả",
    code: "195",
    parent_code: "22",
    path_with_type: "Thành phố Cẩm Phả, Tỉnh Quảng Ninh",
  },
  {
    name: "Uông Bí",
    code: "196",
    parent_code: "22",
    path_with_type: "Thành phố Uông Bí, Tỉnh Quảng Ninh",
  },
  {
    name: "Bình Liêu",
    code: "198",
    parent_code: "22",
    path_with_type: "Huyện Bình Liêu, Tỉnh Quảng Ninh",
  },
  {
    name: "Tiên Yên",
    code: "199",
    parent_code: "22",
    path_with_type: "Huyện Tiên Yên, Tỉnh Quảng Ninh",
  },
  {
    name: "Đầm Hà",
    code: "200",
    parent_code: "22",
    path_with_type: "Huyện Đầm Hà, Tỉnh Quảng Ninh",
  },
  {
    name: "Hải Hà",
    code: "201",
    parent_code: "22",
    path_with_type: "Huyện Hải Hà, Tỉnh Quảng Ninh",
  },
  {
    name: "Ba Chẽ",
    code: "202",
    parent_code: "22",
    path_with_type: "Huyện Ba Chẽ, Tỉnh Quảng Ninh",
  },
  {
    name: "Vân Đồn",
    code: "203",
    parent_code: "22",
    path_with_type: "Huyện Vân Đồn, Tỉnh Quảng Ninh",
  },
  {
    name: "Hoành Bồ",
    code: "204",
    parent_code: "22",
    path_with_type: "Huyện Hoành Bồ, Tỉnh Quảng Ninh",
  },
  {
    name: "Đông Triều",
    code: "205",
    parent_code: "22",
    path_with_type: "Thị xã Đông Triều, Tỉnh Quảng Ninh",
  },
  {
    name: "Quảng Yên",
    code: "206",
    parent_code: "22",
    path_with_type: "Thị xã Quảng Yên, Tỉnh Quảng Ninh",
  },
  {
    name: "Cô Tô",
    code: "207",
    parent_code: "22",
    path_with_type: "Huyện Cô Tô, Tỉnh Quảng Ninh",
  },
  {
    name: "Bắc Giang",
    code: "213",
    parent_code: "24",
    path_with_type: "Thành phố Bắc Giang, Tỉnh Bắc Giang",
  },
  {
    name: "Yên Thế",
    code: "215",
    parent_code: "24",
    path_with_type: "Huyện Yên Thế, Tỉnh Bắc Giang",
  },
  {
    name: "Tân Yên",
    code: "216",
    parent_code: "24",
    path_with_type: "Huyện Tân Yên, Tỉnh Bắc Giang",
  },
  {
    name: "Lạng Giang",
    code: "217",
    parent_code: "24",
    path_with_type: "Huyện Lạng Giang, Tỉnh Bắc Giang",
  },
  {
    name: "Lục Nam",
    code: "218",
    parent_code: "24",
    path_with_type: "Huyện Lục Nam, Tỉnh Bắc Giang",
  },
  {
    name: "Lục Ngạn",
    code: "219",
    parent_code: "24",
    path_with_type: "Huyện Lục Ngạn, Tỉnh Bắc Giang",
  },
  {
    name: "Sơn Động",
    code: "220",
    parent_code: "24",
    path_with_type: "Huyện Sơn Động, Tỉnh Bắc Giang",
  },
  {
    name: "Yên Dũng",
    code: "221",
    parent_code: "24",
    path_with_type: "Huyện Yên Dũng, Tỉnh Bắc Giang",
  },
  {
    name: "Việt Yên",
    code: "222",
    parent_code: "24",
    path_with_type: "Huyện Việt Yên, Tỉnh Bắc Giang",
  },
  {
    name: "Hiệp Hòa",
    code: "223",
    parent_code: "24",
    path_with_type: "Huyện Hiệp Hòa, Tỉnh Bắc Giang",
  },
  {
    name: "Việt Trì",
    code: "227",
    parent_code: "25",
    path_with_type: "Thành phố Việt Trì, Tỉnh Phú Thọ",
  },
  {
    name: "Phú Thọ",
    code: "228",
    parent_code: "25",
    path_with_type: "Thị xã Phú Thọ, Tỉnh Phú Thọ",
  },
  {
    name: "Đoan Hùng",
    code: "230",
    parent_code: "25",
    path_with_type: "Huyện Đoan Hùng, Tỉnh Phú Thọ",
  },
  {
    name: "Hạ Hoà",
    code: "231",
    parent_code: "25",
    path_with_type: "Huyện Hạ Hoà, Tỉnh Phú Thọ",
  },
  {
    name: "Thanh Ba",
    code: "232",
    parent_code: "25",
    path_with_type: "Huyện Thanh Ba, Tỉnh Phú Thọ",
  },
  {
    name: "Phù Ninh",
    code: "233",
    parent_code: "25",
    path_with_type: "Huyện Phù Ninh, Tỉnh Phú Thọ",
  },
  {
    name: "Yên Lập",
    code: "234",
    parent_code: "25",
    path_with_type: "Huyện Yên Lập, Tỉnh Phú Thọ",
  },
  {
    name: "Cẩm Khê",
    code: "235",
    parent_code: "25",
    path_with_type: "Huyện Cẩm Khê, Tỉnh Phú Thọ",
  },
  {
    name: "Tam Nông",
    code: "236",
    parent_code: "25",
    path_with_type: "Huyện Tam Nông, Tỉnh Phú Thọ",
  },
  {
    name: "Lâm Thao",
    code: "237",
    parent_code: "25",
    path_with_type: "Huyện Lâm Thao, Tỉnh Phú Thọ",
  },
  {
    name: "Thanh Sơn",
    code: "238",
    parent_code: "25",
    path_with_type: "Huyện Thanh Sơn, Tỉnh Phú Thọ",
  },
  {
    name: "Thanh Thuỷ",
    code: "239",
    parent_code: "25",
    path_with_type: "Huyện Thanh Thuỷ, Tỉnh Phú Thọ",
  },
  {
    name: "Tân Sơn",
    code: "240",
    parent_code: "25",
    path_with_type: "Huyện Tân Sơn, Tỉnh Phú Thọ",
  },
  {
    name: "Vĩnh Yên",
    code: "243",
    parent_code: "26",
    path_with_type: "Thành phố Vĩnh Yên, Tỉnh Vĩnh Phúc",
  },
  {
    name: "Phúc Yên",
    code: "244",
    parent_code: "26",
    path_with_type: "Thị xã Phúc Yên, Tỉnh Vĩnh Phúc",
  },
  {
    name: "Lập Thạch",
    code: "246",
    parent_code: "26",
    path_with_type: "Huyện Lập Thạch, Tỉnh Vĩnh Phúc",
  },
  {
    name: "Tam Dương",
    code: "247",
    parent_code: "26",
    path_with_type: "Huyện Tam Dương, Tỉnh Vĩnh Phúc",
  },
  {
    name: "Tam Đảo",
    code: "248",
    parent_code: "26",
    path_with_type: "Huyện Tam Đảo, Tỉnh Vĩnh Phúc",
  },
  {
    name: "Bình Xuyên",
    code: "249",
    parent_code: "26",
    path_with_type: "Huyện Bình Xuyên, Tỉnh Vĩnh Phúc",
  },
  {
    name: "Mê Linh",
    code: "250",
    parent_code: "01",
    path_with_type: "Huyện Mê Linh, Thành phố Hà Nội",
  },
  {
    name: "Yên Lạc",
    code: "251",
    parent_code: "26",
    path_with_type: "Huyện Yên Lạc, Tỉnh Vĩnh Phúc",
  },
  {
    name: "Vĩnh Tường",
    code: "252",
    parent_code: "26",
    path_with_type: "Huyện Vĩnh Tường, Tỉnh Vĩnh Phúc",
  },
  {
    name: "Sông Lô",
    code: "253",
    parent_code: "26",
    path_with_type: "Huyện Sông Lô, Tỉnh Vĩnh Phúc",
  },
  {
    name: "Bắc Ninh",
    code: "256",
    parent_code: "27",
    path_with_type: "Thành phố Bắc Ninh, Tỉnh Bắc Ninh",
  },
  {
    name: "Yên Phong",
    code: "258",
    parent_code: "27",
    path_with_type: "Huyện Yên Phong, Tỉnh Bắc Ninh",
  },
  {
    name: "Quế Võ",
    code: "259",
    parent_code: "27",
    path_with_type: "Huyện Quế Võ, Tỉnh Bắc Ninh",
  },
  {
    name: "Tiên Du",
    code: "260",
    parent_code: "27",
    path_with_type: "Huyện Tiên Du, Tỉnh Bắc Ninh",
  },
  {
    name: "Từ Sơn",
    code: "261",
    parent_code: "27",
    path_with_type: "Thị xã Từ Sơn, Tỉnh Bắc Ninh",
  },
  {
    name: "Thuận Thành",
    code: "262",
    parent_code: "27",
    path_with_type: "Huyện Thuận Thành, Tỉnh Bắc Ninh",
  },
  {
    name: "Gia Bình",
    code: "263",
    parent_code: "27",
    path_with_type: "Huyện Gia Bình, Tỉnh Bắc Ninh",
  },
  {
    name: "Lương Tài",
    code: "264",
    parent_code: "27",
    path_with_type: "Huyện Lương Tài, Tỉnh Bắc Ninh",
  },
  {
    name: "Hà Đông",
    code: "268",
    parent_code: "01",
    path_with_type: "Quận Hà Đông, Thành phố Hà Nội",
  },
  {
    name: "Sơn Tây",
    code: "269",
    parent_code: "01",
    path_with_type: "Thị xã Sơn Tây, Thành phố Hà Nội",
  },
  {
    name: "Ba Vì",
    code: "271",
    parent_code: "01",
    path_with_type: "Huyện Ba Vì, Thành phố Hà Nội",
  },
  {
    name: "Phúc Thọ",
    code: "272",
    parent_code: "01",
    path_with_type: "Huyện Phúc Thọ, Thành phố Hà Nội",
  },
  {
    name: "Đan Phượng",
    code: "273",
    parent_code: "01",
    path_with_type: "Huyện Đan Phượng, Thành phố Hà Nội",
  },
  {
    name: "Hoài Đức",
    code: "274",
    parent_code: "01",
    path_with_type: "Huyện Hoài Đức, Thành phố Hà Nội",
  },
  {
    name: "Quốc Oai",
    code: "275",
    parent_code: "01",
    path_with_type: "Huyện Quốc Oai, Thành phố Hà Nội",
  },
  {
    name: "Thạch Thất",
    code: "276",
    parent_code: "01",
    path_with_type: "Huyện Thạch Thất, Thành phố Hà Nội",
  },
  {
    name: "Chương Mỹ",
    code: "277",
    parent_code: "01",
    path_with_type: "Huyện Chương Mỹ, Thành phố Hà Nội",
  },
  {
    name: "Thanh Oai",
    code: "278",
    parent_code: "01",
    path_with_type: "Huyện Thanh Oai, Thành phố Hà Nội",
  },
  {
    name: "Thường Tín",
    code: "279",
    parent_code: "01",
    path_with_type: "Huyện Thường Tín, Thành phố Hà Nội",
  },
  {
    name: "Phú Xuyên",
    code: "280",
    parent_code: "01",
    path_with_type: "Huyện Phú Xuyên, Thành phố Hà Nội",
  },
  {
    name: "Ứng Hòa",
    code: "281",
    parent_code: "01",
    path_with_type: "Huyện Ứng Hòa, Thành phố Hà Nội",
  },
  {
    name: "Mỹ Đức",
    code: "282",
    parent_code: "01",
    path_with_type: "Huyện Mỹ Đức, Thành phố Hà Nội",
  },
  {
    name: "Hải Dương",
    code: "288",
    parent_code: "30",
    path_with_type: "Thành phố Hải Dương, Tỉnh Hải Dương",
  },
  {
    name: "Chí Linh",
    code: "290",
    parent_code: "30",
    path_with_type: "Thị xã Chí Linh, Tỉnh Hải Dương",
  },
  {
    name: "Nam Sách",
    code: "291",
    parent_code: "30",
    path_with_type: "Huyện Nam Sách, Tỉnh Hải Dương",
  },
  {
    name: "Kinh Môn",
    code: "292",
    parent_code: "30",
    path_with_type: "Huyện Kinh Môn, Tỉnh Hải Dương",
  },
  {
    name: "Kim Thành",
    code: "293",
    parent_code: "30",
    path_with_type: "Huyện Kim Thành, Tỉnh Hải Dương",
  },
  {
    name: "Thanh Hà",
    code: "294",
    parent_code: "30",
    path_with_type: "Huyện Thanh Hà, Tỉnh Hải Dương",
  },
  {
    name: "Cẩm Giàng",
    code: "295",
    parent_code: "30",
    path_with_type: "Huyện Cẩm Giàng, Tỉnh Hải Dương",
  },
  {
    name: "Bình Giang",
    code: "296",
    parent_code: "30",
    path_with_type: "Huyện Bình Giang, Tỉnh Hải Dương",
  },
  {
    name: "Gia Lộc",
    code: "297",
    parent_code: "30",
    path_with_type: "Huyện Gia Lộc, Tỉnh Hải Dương",
  },
  {
    name: "Tứ Kỳ",
    code: "298",
    parent_code: "30",
    path_with_type: "Huyện Tứ Kỳ, Tỉnh Hải Dương",
  },
  {
    name: "Ninh Giang",
    code: "299",
    parent_code: "30",
    path_with_type: "Huyện Ninh Giang, Tỉnh Hải Dương",
  },
  {
    name: "Thanh Miện",
    code: "300",
    parent_code: "30",
    path_with_type: "Huyện Thanh Miện, Tỉnh Hải Dương",
  },
  {
    name: "Hồng Bàng",
    code: "303",
    parent_code: "31",
    path_with_type: "Quận Hồng Bàng, Thành phố Hải Phòng",
  },
  {
    name: "Ngô Quyền",
    code: "304",
    parent_code: "31",
    path_with_type: "Quận Ngô Quyền, Thành phố Hải Phòng",
  },
  {
    name: "Lê Chân",
    code: "305",
    parent_code: "31",
    path_with_type: "Quận Lê Chân, Thành phố Hải Phòng",
  },
  {
    name: "Hải An",
    code: "306",
    parent_code: "31",
    path_with_type: "Quận Hải An, Thành phố Hải Phòng",
  },
  {
    name: "Kiến An",
    code: "307",
    parent_code: "31",
    path_with_type: "Quận Kiến An, Thành phố Hải Phòng",
  },
  {
    name: "Đồ Sơn",
    code: "308",
    parent_code: "31",
    path_with_type: "Quận Đồ Sơn, Thành phố Hải Phòng",
  },
  {
    name: "Dương Kinh",
    code: "309",
    parent_code: "31",
    path_with_type: "Quận Dương Kinh, Thành phố Hải Phòng",
  },
  {
    name: "Thuỷ Nguyên",
    code: "311",
    parent_code: "31",
    path_with_type: "Huyện Thuỷ Nguyên, Thành phố Hải Phòng",
  },
  {
    name: "An Dương",
    code: "312",
    parent_code: "31",
    path_with_type: "Huyện An Dương, Thành phố Hải Phòng",
  },
  {
    name: "An Lão",
    code: "313",
    parent_code: "31",
    path_with_type: "Huyện An Lão, Thành phố Hải Phòng",
  },
  {
    name: "Kiến Thuỵ",
    code: "314",
    parent_code: "31",
    path_with_type: "Huyện Kiến Thuỵ, Thành phố Hải Phòng",
  },
  {
    name: "Tiên Lãng",
    code: "315",
    parent_code: "31",
    path_with_type: "Huyện Tiên Lãng, Thành phố Hải Phòng",
  },
  {
    name: "Vĩnh Bảo",
    code: "316",
    parent_code: "31",
    path_with_type: "Huyện Vĩnh Bảo, Thành phố Hải Phòng",
  },
  {
    name: "Cát Hải",
    code: "317",
    parent_code: "31",
    path_with_type: "Huyện Cát Hải, Thành phố Hải Phòng",
  },
  {
    name: "Hưng Yên",
    code: "323",
    parent_code: "33",
    path_with_type: "Thành phố Hưng Yên, Tỉnh Hưng Yên",
  },
  {
    name: "Văn Lâm",
    code: "325",
    parent_code: "33",
    path_with_type: "Huyện Văn Lâm, Tỉnh Hưng Yên",
  },
  {
    name: "Văn Giang",
    code: "326",
    parent_code: "33",
    path_with_type: "Huyện Văn Giang, Tỉnh Hưng Yên",
  },
  {
    name: "Yên Mỹ",
    code: "327",
    parent_code: "33",
    path_with_type: "Huyện Yên Mỹ, Tỉnh Hưng Yên",
  },
  {
    name: "Mỹ Hào",
    code: "328",
    parent_code: "33",
    path_with_type: "Huyện Mỹ Hào, Tỉnh Hưng Yên",
  },
  {
    name: "Ân Thi",
    code: "329",
    parent_code: "33",
    path_with_type: "Huyện Ân Thi, Tỉnh Hưng Yên",
  },
  {
    name: "Khoái Châu",
    code: "330",
    parent_code: "33",
    path_with_type: "Huyện Khoái Châu, Tỉnh Hưng Yên",
  },
  {
    name: "Kim Động",
    code: "331",
    parent_code: "33",
    path_with_type: "Huyện Kim Động, Tỉnh Hưng Yên",
  },
  {
    name: "Tiên Lữ",
    code: "332",
    parent_code: "33",
    path_with_type: "Huyện Tiên Lữ, Tỉnh Hưng Yên",
  },
  {
    name: "Phù Cừ",
    code: "333",
    parent_code: "33",
    path_with_type: "Huyện Phù Cừ, Tỉnh Hưng Yên",
  },
  {
    name: "Thái Bình",
    code: "336",
    parent_code: "34",
    path_with_type: "Thành phố Thái Bình, Tỉnh Thái Bình",
  },
  {
    name: "Quỳnh Phụ",
    code: "338",
    parent_code: "34",
    path_with_type: "Huyện Quỳnh Phụ, Tỉnh Thái Bình",
  },
  {
    name: "Hưng Hà",
    code: "339",
    parent_code: "34",
    path_with_type: "Huyện Hưng Hà, Tỉnh Thái Bình",
  },
  {
    name: "Đông Hưng",
    code: "340",
    parent_code: "34",
    path_with_type: "Huyện Đông Hưng, Tỉnh Thái Bình",
  },
  {
    name: "Thái Thụy",
    code: "341",
    parent_code: "34",
    path_with_type: "Huyện Thái Thụy, Tỉnh Thái Bình",
  },
  {
    name: "Tiền Hải",
    code: "342",
    parent_code: "34",
    path_with_type: "Huyện Tiền Hải, Tỉnh Thái Bình",
  },
  {
    name: "Kiến Xương",
    code: "343",
    parent_code: "34",
    path_with_type: "Huyện Kiến Xương, Tỉnh Thái Bình",
  },
  {
    name: "Vũ Thư",
    code: "344",
    parent_code: "34",
    path_with_type: "Huyện Vũ Thư, Tỉnh Thái Bình",
  },
  {
    name: "Phủ Lý",
    code: "347",
    parent_code: "35",
    path_with_type: "Thành phố Phủ Lý, Tỉnh Hà Nam",
  },
  {
    name: "Duy Tiên",
    code: "349",
    parent_code: "35",
    path_with_type: "Huyện Duy Tiên, Tỉnh Hà Nam",
  },
  {
    name: "Kim Bảng",
    code: "350",
    parent_code: "35",
    path_with_type: "Huyện Kim Bảng, Tỉnh Hà Nam",
  },
  {
    name: "Thanh Liêm",
    code: "351",
    parent_code: "35",
    path_with_type: "Huyện Thanh Liêm, Tỉnh Hà Nam",
  },
  {
    name: "Bình Lục",
    code: "352",
    parent_code: "35",
    path_with_type: "Huyện Bình Lục, Tỉnh Hà Nam",
  },
  {
    name: "Lý Nhân",
    code: "353",
    parent_code: "35",
    path_with_type: "Huyện Lý Nhân, Tỉnh Hà Nam",
  },
  {
    name: "Nam Định",
    code: "356",
    parent_code: "36",
    path_with_type: "Thành phố Nam Định, Tỉnh Nam Định",
  },
  {
    name: "Mỹ Lộc",
    code: "358",
    parent_code: "36",
    path_with_type: "Huyện Mỹ Lộc, Tỉnh Nam Định",
  },
  {
    name: "Vụ Bản",
    code: "359",
    parent_code: "36",
    path_with_type: "Huyện Vụ Bản, Tỉnh Nam Định",
  },
  {
    name: "Ý Yên",
    code: "360",
    parent_code: "36",
    path_with_type: "Huyện Ý Yên, Tỉnh Nam Định",
  },
  {
    name: "Nghĩa Hưng",
    code: "361",
    parent_code: "36",
    path_with_type: "Huyện Nghĩa Hưng, Tỉnh Nam Định",
  },
  {
    name: "Nam Trực",
    code: "362",
    parent_code: "36",
    path_with_type: "Huyện Nam Trực, Tỉnh Nam Định",
  },
  {
    name: "Trực Ninh",
    code: "363",
    parent_code: "36",
    path_with_type: "Huyện Trực Ninh, Tỉnh Nam Định",
  },
  {
    name: "Xuân Trường",
    code: "364",
    parent_code: "36",
    path_with_type: "Huyện Xuân Trường, Tỉnh Nam Định",
  },
  {
    name: "Giao Thủy",
    code: "365",
    parent_code: "36",
    path_with_type: "Huyện Giao Thủy, Tỉnh Nam Định",
  },
  {
    name: "Hải Hậu",
    code: "366",
    parent_code: "36",
    path_with_type: "Huyện Hải Hậu, Tỉnh Nam Định",
  },
  {
    name: "Ninh Bình",
    code: "369",
    parent_code: "37",
    path_with_type: "Thành phố Ninh Bình, Tỉnh Ninh Bình",
  },
  {
    name: "Tam Điệp",
    code: "370",
    parent_code: "37",
    path_with_type: "Thành phố Tam Điệp, Tỉnh Ninh Bình",
  },
  {
    name: "Nho Quan",
    code: "372",
    parent_code: "37",
    path_with_type: "Huyện Nho Quan, Tỉnh Ninh Bình",
  },
  {
    name: "Gia Viễn",
    code: "373",
    parent_code: "37",
    path_with_type: "Huyện Gia Viễn, Tỉnh Ninh Bình",
  },
  {
    name: "Hoa Lư",
    code: "374",
    parent_code: "37",
    path_with_type: "Huyện Hoa Lư, Tỉnh Ninh Bình",
  },
  {
    name: "Yên Khánh",
    code: "375",
    parent_code: "37",
    path_with_type: "Huyện Yên Khánh, Tỉnh Ninh Bình",
  },
  {
    name: "Kim Sơn",
    code: "376",
    parent_code: "37",
    path_with_type: "Huyện Kim Sơn, Tỉnh Ninh Bình",
  },
  {
    name: "Yên Mô",
    code: "377",
    parent_code: "37",
    path_with_type: "Huyện Yên Mô, Tỉnh Ninh Bình",
  },
  {
    name: "Thanh Hóa",
    code: "380",
    parent_code: "38",
    path_with_type: "Thành phố Thanh Hóa, Tỉnh Thanh Hóa",
  },
  {
    name: "Bỉm Sơn",
    code: "381",
    parent_code: "38",
    path_with_type: "Thị xã Bỉm Sơn, Tỉnh Thanh Hóa",
  },
  {
    name: "Sầm Sơn",
    code: "382",
    parent_code: "38",
    path_with_type: "Thành phố Sầm Sơn, Tỉnh Thanh Hóa",
  },
  {
    name: "Mường Lát",
    code: "384",
    parent_code: "38",
    path_with_type: "Huyện Mường Lát, Tỉnh Thanh Hóa",
  },
  {
    name: "Quan Hóa",
    code: "385",
    parent_code: "38",
    path_with_type: "Huyện Quan Hóa, Tỉnh Thanh Hóa",
  },
  {
    name: "Bá Thước",
    code: "386",
    parent_code: "38",
    path_with_type: "Huyện Bá Thước, Tỉnh Thanh Hóa",
  },
  {
    name: "Quan Sơn",
    code: "387",
    parent_code: "38",
    path_with_type: "Huyện Quan Sơn, Tỉnh Thanh Hóa",
  },
  {
    name: "Lang Chánh",
    code: "388",
    parent_code: "38",
    path_with_type: "Huyện Lang Chánh, Tỉnh Thanh Hóa",
  },
  {
    name: "Ngọc Lặc",
    code: "389",
    parent_code: "38",
    path_with_type: "Huyện Ngọc Lặc, Tỉnh Thanh Hóa",
  },
  {
    name: "Cẩm Thủy",
    code: "390",
    parent_code: "38",
    path_with_type: "Huyện Cẩm Thủy, Tỉnh Thanh Hóa",
  },
  {
    name: "Thạch Thành",
    code: "391",
    parent_code: "38",
    path_with_type: "Huyện Thạch Thành, Tỉnh Thanh Hóa",
  },
  {
    name: "Hà Trung",
    code: "392",
    parent_code: "38",
    path_with_type: "Huyện Hà Trung, Tỉnh Thanh Hóa",
  },
  {
    name: "Vĩnh Lộc",
    code: "393",
    parent_code: "38",
    path_with_type: "Huyện Vĩnh Lộc, Tỉnh Thanh Hóa",
  },
  {
    name: "Yên Định",
    code: "394",
    parent_code: "38",
    path_with_type: "Huyện Yên Định, Tỉnh Thanh Hóa",
  },
  {
    name: "Thọ Xuân",
    code: "395",
    parent_code: "38",
    path_with_type: "Huyện Thọ Xuân, Tỉnh Thanh Hóa",
  },
  {
    name: "Thường Xuân",
    code: "396",
    parent_code: "38",
    path_with_type: "Huyện Thường Xuân, Tỉnh Thanh Hóa",
  },
  {
    name: "Triệu Sơn",
    code: "397",
    parent_code: "38",
    path_with_type: "Huyện Triệu Sơn, Tỉnh Thanh Hóa",
  },
  {
    name: "Thiệu Hóa",
    code: "398",
    parent_code: "38",
    path_with_type: "Huyện Thiệu Hóa, Tỉnh Thanh Hóa",
  },
  {
    name: "Hoằng Hóa",
    code: "399",
    parent_code: "38",
    path_with_type: "Huyện Hoằng Hóa, Tỉnh Thanh Hóa",
  },
  {
    name: "Hậu Lộc",
    code: "400",
    parent_code: "38",
    path_with_type: "Huyện Hậu Lộc, Tỉnh Thanh Hóa",
  },
  {
    name: "Nga Sơn",
    code: "401",
    parent_code: "38",
    path_with_type: "Huyện Nga Sơn, Tỉnh Thanh Hóa",
  },
  {
    name: "Như Xuân",
    code: "402",
    parent_code: "38",
    path_with_type: "Huyện Như Xuân, Tỉnh Thanh Hóa",
  },
  {
    name: "Như Thanh",
    code: "403",
    parent_code: "38",
    path_with_type: "Huyện Như Thanh, Tỉnh Thanh Hóa",
  },
  {
    name: "Nông Cống",
    code: "404",
    parent_code: "38",
    path_with_type: "Huyện Nông Cống, Tỉnh Thanh Hóa",
  },
  {
    name: "Đông Sơn",
    code: "405",
    parent_code: "38",
    path_with_type: "Huyện Đông Sơn, Tỉnh Thanh Hóa",
  },
  {
    name: "Quảng Xương",
    code: "406",
    parent_code: "38",
    path_with_type: "Huyện Quảng Xương, Tỉnh Thanh Hóa",
  },
  {
    name: "Tĩnh Gia",
    code: "407",
    parent_code: "38",
    path_with_type: "Huyện Tĩnh Gia, Tỉnh Thanh Hóa",
  },
  {
    name: "Vinh",
    code: "412",
    parent_code: "40",
    path_with_type: "Thành phố Vinh, Tỉnh Nghệ An",
  },
  {
    name: "Cửa Lò",
    code: "413",
    parent_code: "40",
    path_with_type: "Thị xã Cửa Lò, Tỉnh Nghệ An",
  },
  {
    name: "Thái Hoà",
    code: "414",
    parent_code: "40",
    path_with_type: "Thị xã Thái Hoà, Tỉnh Nghệ An",
  },
  {
    name: "Quế Phong",
    code: "415",
    parent_code: "40",
    path_with_type: "Huyện Quế Phong, Tỉnh Nghệ An",
  },
  {
    name: "Quỳ Châu",
    code: "416",
    parent_code: "40",
    path_with_type: "Huyện Quỳ Châu, Tỉnh Nghệ An",
  },
  {
    name: "Kỳ Sơn",
    code: "417",
    parent_code: "40",
    path_with_type: "Huyện Kỳ Sơn, Tỉnh Nghệ An",
  },
  {
    name: "Tương Dương",
    code: "418",
    parent_code: "40",
    path_with_type: "Huyện Tương Dương, Tỉnh Nghệ An",
  },
  {
    name: "Nghĩa Đàn",
    code: "419",
    parent_code: "40",
    path_with_type: "Huyện Nghĩa Đàn, Tỉnh Nghệ An",
  },
  {
    name: "Quỳ Hợp",
    code: "420",
    parent_code: "40",
    path_with_type: "Huyện Quỳ Hợp, Tỉnh Nghệ An",
  },
  {
    name: "Quỳnh Lưu",
    code: "421",
    parent_code: "40",
    path_with_type: "Huyện Quỳnh Lưu, Tỉnh Nghệ An",
  },
  {
    name: "Con Cuông",
    code: "422",
    parent_code: "40",
    path_with_type: "Huyện Con Cuông, Tỉnh Nghệ An",
  },
  {
    name: "Tân Kỳ",
    code: "423",
    parent_code: "40",
    path_with_type: "Huyện Tân Kỳ, Tỉnh Nghệ An",
  },
  {
    name: "Anh Sơn",
    code: "424",
    parent_code: "40",
    path_with_type: "Huyện Anh Sơn, Tỉnh Nghệ An",
  },
  {
    name: "Diễn Châu",
    code: "425",
    parent_code: "40",
    path_with_type: "Huyện Diễn Châu, Tỉnh Nghệ An",
  },
  {
    name: "Yên Thành",
    code: "426",
    parent_code: "40",
    path_with_type: "Huyện Yên Thành, Tỉnh Nghệ An",
  },
  {
    name: "Đô Lương",
    code: "427",
    parent_code: "40",
    path_with_type: "Huyện Đô Lương, Tỉnh Nghệ An",
  },
  {
    name: "Thanh Chương",
    code: "428",
    parent_code: "40",
    path_with_type: "Huyện Thanh Chương, Tỉnh Nghệ An",
  },
  {
    name: "Nghi Lộc",
    code: "429",
    parent_code: "40",
    path_with_type: "Huyện Nghi Lộc, Tỉnh Nghệ An",
  },
  {
    name: "Nam Đàn",
    code: "430",
    parent_code: "40",
    path_with_type: "Huyện Nam Đàn, Tỉnh Nghệ An",
  },
  {
    name: "Hưng Nguyên",
    code: "431",
    parent_code: "40",
    path_with_type: "Huyện Hưng Nguyên, Tỉnh Nghệ An",
  },
  {
    name: "Hoàng Mai",
    code: "432",
    parent_code: "40",
    path_with_type: "Thị xã Hoàng Mai, Tỉnh Nghệ An",
  },
  {
    name: "Hà Tĩnh",
    code: "436",
    parent_code: "42",
    path_with_type: "Thành phố Hà Tĩnh, Tỉnh Hà Tĩnh",
  },
  {
    name: "Hồng Lĩnh",
    code: "437",
    parent_code: "42",
    path_with_type: "Thị xã Hồng Lĩnh, Tỉnh Hà Tĩnh",
  },
  {
    name: "Hương Sơn",
    code: "439",
    parent_code: "42",
    path_with_type: "Huyện Hương Sơn, Tỉnh Hà Tĩnh",
  },
  {
    name: "Đức Thọ",
    code: "440",
    parent_code: "42",
    path_with_type: "Huyện Đức Thọ, Tỉnh Hà Tĩnh",
  },
  {
    name: "Vũ Quang",
    code: "441",
    parent_code: "42",
    path_with_type: "Huyện Vũ Quang, Tỉnh Hà Tĩnh",
  },
  {
    name: "Nghi Xuân",
    code: "442",
    parent_code: "42",
    path_with_type: "Huyện Nghi Xuân, Tỉnh Hà Tĩnh",
  },
  {
    name: "Can Lộc",
    code: "443",
    parent_code: "42",
    path_with_type: "Huyện Can Lộc, Tỉnh Hà Tĩnh",
  },
  {
    name: "Hương Khê",
    code: "444",
    parent_code: "42",
    path_with_type: "Huyện Hương Khê, Tỉnh Hà Tĩnh",
  },
  {
    name: "Thạch Hà",
    code: "445",
    parent_code: "42",
    path_with_type: "Huyện Thạch Hà, Tỉnh Hà Tĩnh",
  },
  {
    name: "Cẩm Xuyên",
    code: "446",
    parent_code: "42",
    path_with_type: "Huyện Cẩm Xuyên, Tỉnh Hà Tĩnh",
  },
  {
    name: "Kỳ Anh",
    code: "447",
    parent_code: "42",
    path_with_type: "Huyện Kỳ Anh, Tỉnh Hà Tĩnh",
  },
  {
    name: "Lộc Hà",
    code: "448",
    parent_code: "42",
    path_with_type: "Huyện Lộc Hà, Tỉnh Hà Tĩnh",
  },
  {
    name: "Kỳ Anh",
    code: "449",
    parent_code: "42",
    path_with_type: "Thị xã Kỳ Anh, Tỉnh Hà Tĩnh",
  },
  {
    name: "Đồng Hới",
    code: "450",
    parent_code: "44",
    path_with_type: "Thành Phố Đồng Hới, Tỉnh Quảng Bình",
  },
  {
    name: "Minh Hóa",
    code: "452",
    parent_code: "44",
    path_with_type: "Huyện Minh Hóa, Tỉnh Quảng Bình",
  },
  {
    name: "Tuyên Hóa",
    code: "453",
    parent_code: "44",
    path_with_type: "Huyện Tuyên Hóa, Tỉnh Quảng Bình",
  },
  {
    name: "Quảng Trạch",
    code: "454",
    parent_code: "44",
    path_with_type: "Huyện Quảng Trạch, Tỉnh Quảng Bình",
  },
  {
    name: "Bố Trạch",
    code: "455",
    parent_code: "44",
    path_with_type: "Huyện Bố Trạch, Tỉnh Quảng Bình",
  },
  {
    name: "Quảng Ninh",
    code: "456",
    parent_code: "44",
    path_with_type: "Huyện Quảng Ninh, Tỉnh Quảng Bình",
  },
  {
    name: "Lệ Thủy",
    code: "457",
    parent_code: "44",
    path_with_type: "Huyện Lệ Thủy, Tỉnh Quảng Bình",
  },
  {
    name: "Ba Đồn",
    code: "458",
    parent_code: "44",
    path_with_type: "Thị xã Ba Đồn, Tỉnh Quảng Bình",
  },
  {
    name: "Đông Hà",
    code: "461",
    parent_code: "45",
    path_with_type: "Thành phố Đông Hà, Tỉnh Quảng Trị",
  },
  {
    name: "Quảng Trị",
    code: "462",
    parent_code: "45",
    path_with_type: "Thị xã Quảng Trị, Tỉnh Quảng Trị",
  },
  {
    name: "Vĩnh Linh",
    code: "464",
    parent_code: "45",
    path_with_type: "Huyện Vĩnh Linh, Tỉnh Quảng Trị",
  },
  {
    name: "Hướng Hóa",
    code: "465",
    parent_code: "45",
    path_with_type: "Huyện Hướng Hóa, Tỉnh Quảng Trị",
  },
  {
    name: "Gio Linh",
    code: "466",
    parent_code: "45",
    path_with_type: "Huyện Gio Linh, Tỉnh Quảng Trị",
  },
  {
    name: "Đa Krông",
    code: "467",
    parent_code: "45",
    path_with_type: "Huyện Đa Krông, Tỉnh Quảng Trị",
  },
  {
    name: "Cam Lộ",
    code: "468",
    parent_code: "45",
    path_with_type: "Huyện Cam Lộ, Tỉnh Quảng Trị",
  },
  {
    name: "Triệu Phong",
    code: "469",
    parent_code: "45",
    path_with_type: "Huyện Triệu Phong, Tỉnh Quảng Trị",
  },
  {
    name: "Hải Lăng",
    code: "470",
    parent_code: "45",
    path_with_type: "Huyện Hải Lăng, Tỉnh Quảng Trị",
  },
  {
    name: "Huế",
    code: "474",
    parent_code: "46",
    path_with_type: "Thành phố Huế, Tỉnh Thừa Thiên Huế",
  },
  {
    name: "Phong Điền",
    code: "476",
    parent_code: "46",
    path_with_type: "Huyện Phong Điền, Tỉnh Thừa Thiên Huế",
  },
  {
    name: "Quảng Điền",
    code: "477",
    parent_code: "46",
    path_with_type: "Huyện Quảng Điền, Tỉnh Thừa Thiên Huế",
  },
  {
    name: "Phú Vang",
    code: "478",
    parent_code: "46",
    path_with_type: "Huyện Phú Vang, Tỉnh Thừa Thiên Huế",
  },
  {
    name: "Hương Thủy",
    code: "479",
    parent_code: "46",
    path_with_type: "Thị xã Hương Thủy, Tỉnh Thừa Thiên Huế",
  },
  {
    name: "Hương Trà",
    code: "480",
    parent_code: "46",
    path_with_type: "Thị xã Hương Trà, Tỉnh Thừa Thiên Huế",
  },
  {
    name: "A Lưới",
    code: "481",
    parent_code: "46",
    path_with_type: "Huyện A Lưới, Tỉnh Thừa Thiên Huế",
  },
  {
    name: "Phú Lộc",
    code: "482",
    parent_code: "46",
    path_with_type: "Huyện Phú Lộc, Tỉnh Thừa Thiên Huế",
  },
  {
    name: "Nam Đông",
    code: "483",
    parent_code: "46",
    path_with_type: "Huyện Nam Đông, Tỉnh Thừa Thiên Huế",
  },
  {
    name: "Liên Chiểu",
    code: "490",
    parent_code: "48",
    path_with_type: "Quận Liên Chiểu, Thành phố Đà Nẵng",
  },
  {
    name: "Thanh Khê",
    code: "491",
    parent_code: "48",
    path_with_type: "Quận Thanh Khê, Thành phố Đà Nẵng",
  },
  {
    name: "Hải Châu",
    code: "492",
    parent_code: "48",
    path_with_type: "Quận Hải Châu, Thành phố Đà Nẵng",
  },
  {
    name: "Sơn Trà",
    code: "493",
    parent_code: "48",
    path_with_type: "Quận Sơn Trà, Thành phố Đà Nẵng",
  },
  {
    name: "Ngũ Hành Sơn",
    code: "494",
    parent_code: "48",
    path_with_type: "Quận Ngũ Hành Sơn, Thành phố Đà Nẵng",
  },
  {
    name: "Cẩm Lệ",
    code: "495",
    parent_code: "48",
    path_with_type: "Quận Cẩm Lệ, Thành phố Đà Nẵng",
  },
  {
    name: "Hòa Vang",
    code: "497",
    parent_code: "48",
    path_with_type: "Huyện Hòa Vang, Thành phố Đà Nẵng",
  },
  {
    name: "Tam Kỳ",
    code: "502",
    parent_code: "49",
    path_with_type: "Thành phố Tam Kỳ, Tỉnh Quảng Nam",
  },
  {
    name: "Hội An",
    code: "503",
    parent_code: "49",
    path_with_type: "Thành phố Hội An, Tỉnh Quảng Nam",
  },
  {
    name: "Tây Giang",
    code: "504",
    parent_code: "49",
    path_with_type: "Huyện Tây Giang, Tỉnh Quảng Nam",
  },
  {
    name: "Đông Giang",
    code: "505",
    parent_code: "49",
    path_with_type: "Huyện Đông Giang, Tỉnh Quảng Nam",
  },
  {
    name: "Đại Lộc",
    code: "506",
    parent_code: "49",
    path_with_type: "Huyện Đại Lộc, Tỉnh Quảng Nam",
  },
  {
    name: "Điện Bàn",
    code: "507",
    parent_code: "49",
    path_with_type: "Thị xã Điện Bàn, Tỉnh Quảng Nam",
  },
  {
    name: "Duy Xuyên",
    code: "508",
    parent_code: "49",
    path_with_type: "Huyện Duy Xuyên, Tỉnh Quảng Nam",
  },
  {
    name: "Quế Sơn",
    code: "509",
    parent_code: "49",
    path_with_type: "Huyện Quế Sơn, Tỉnh Quảng Nam",
  },
  {
    name: "Nam Giang",
    code: "510",
    parent_code: "49",
    path_with_type: "Huyện Nam Giang, Tỉnh Quảng Nam",
  },
  {
    name: "Phước Sơn",
    code: "511",
    parent_code: "49",
    path_with_type: "Huyện Phước Sơn, Tỉnh Quảng Nam",
  },
  {
    name: "Hiệp Đức",
    code: "512",
    parent_code: "49",
    path_with_type: "Huyện Hiệp Đức, Tỉnh Quảng Nam",
  },
  {
    name: "Thăng Bình",
    code: "513",
    parent_code: "49",
    path_with_type: "Huyện Thăng Bình, Tỉnh Quảng Nam",
  },
  {
    name: "Tiên Phước",
    code: "514",
    parent_code: "49",
    path_with_type: "Huyện Tiên Phước, Tỉnh Quảng Nam",
  },
  {
    name: "Bắc Trà My",
    code: "515",
    parent_code: "49",
    path_with_type: "Huyện Bắc Trà My, Tỉnh Quảng Nam",
  },
  {
    name: "Nam Trà My",
    code: "516",
    parent_code: "49",
    path_with_type: "Huyện Nam Trà My, Tỉnh Quảng Nam",
  },
  {
    name: "Núi Thành",
    code: "517",
    parent_code: "49",
    path_with_type: "Huyện Núi Thành, Tỉnh Quảng Nam",
  },
  {
    name: "Phú Ninh",
    code: "518",
    parent_code: "49",
    path_with_type: "Huyện Phú Ninh, Tỉnh Quảng Nam",
  },
  {
    name: "Nông Sơn",
    code: "519",
    parent_code: "49",
    path_with_type: "Huyện Nông Sơn, Tỉnh Quảng Nam",
  },
  {
    name: "Quảng Ngãi",
    code: "522",
    parent_code: "51",
    path_with_type: "Thành phố Quảng Ngãi, Tỉnh Quảng Ngãi",
  },
  {
    name: "Bình Sơn",
    code: "524",
    parent_code: "51",
    path_with_type: "Huyện Bình Sơn, Tỉnh Quảng Ngãi",
  },
  {
    name: "Trà Bồng",
    code: "525",
    parent_code: "51",
    path_with_type: "Huyện Trà Bồng, Tỉnh Quảng Ngãi",
  },
  {
    name: "Tây Trà",
    code: "526",
    parent_code: "51",
    path_with_type: "Huyện Tây Trà, Tỉnh Quảng Ngãi",
  },
  {
    name: "Sơn Tịnh",
    code: "527",
    parent_code: "51",
    path_with_type: "Huyện Sơn Tịnh, Tỉnh Quảng Ngãi",
  },
  {
    name: "Tư Nghĩa",
    code: "528",
    parent_code: "51",
    path_with_type: "Huyện Tư Nghĩa, Tỉnh Quảng Ngãi",
  },
  {
    name: "Sơn Hà",
    code: "529",
    parent_code: "51",
    path_with_type: "Huyện Sơn Hà, Tỉnh Quảng Ngãi",
  },
  {
    name: "Sơn Tây",
    code: "530",
    parent_code: "51",
    path_with_type: "Huyện Sơn Tây, Tỉnh Quảng Ngãi",
  },
  {
    name: "Minh Long",
    code: "531",
    parent_code: "51",
    path_with_type: "Huyện Minh Long, Tỉnh Quảng Ngãi",
  },
  {
    name: "Nghĩa Hành",
    code: "532",
    parent_code: "51",
    path_with_type: "Huyện Nghĩa Hành, Tỉnh Quảng Ngãi",
  },
  {
    name: "Mộ Đức",
    code: "533",
    parent_code: "51",
    path_with_type: "Huyện Mộ Đức, Tỉnh Quảng Ngãi",
  },
  {
    name: "Đức Phổ",
    code: "534",
    parent_code: "51",
    path_with_type: "Huyện Đức Phổ, Tỉnh Quảng Ngãi",
  },
  {
    name: "Ba Tơ",
    code: "535",
    parent_code: "51",
    path_with_type: "Huyện Ba Tơ, Tỉnh Quảng Ngãi",
  },
  {
    name: "Lý Sơn",
    code: "536",
    parent_code: "51",
    path_with_type: "Huyện Lý Sơn, Tỉnh Quảng Ngãi",
  },
  {
    name: "Qui Nhơn",
    code: "540",
    parent_code: "52",
    path_with_type: "Thành phố Qui Nhơn, Tỉnh Bình Định",
  },
  {
    name: "An Lão",
    code: "542",
    parent_code: "52",
    path_with_type: "Huyện An Lão, Tỉnh Bình Định",
  },
  {
    name: "Hoài Nhơn",
    code: "543",
    parent_code: "52",
    path_with_type: "Huyện Hoài Nhơn, Tỉnh Bình Định",
  },
  {
    name: "Hoài Ân",
    code: "544",
    parent_code: "52",
    path_with_type: "Huyện Hoài Ân, Tỉnh Bình Định",
  },
  {
    name: "Phù Mỹ",
    code: "545",
    parent_code: "52",
    path_with_type: "Huyện Phù Mỹ, Tỉnh Bình Định",
  },
  {
    name: "Vĩnh Thạnh",
    code: "546",
    parent_code: "52",
    path_with_type: "Huyện Vĩnh Thạnh, Tỉnh Bình Định",
  },
  {
    name: "Tây Sơn",
    code: "547",
    parent_code: "52",
    path_with_type: "Huyện Tây Sơn, Tỉnh Bình Định",
  },
  {
    name: "Phù Cát",
    code: "548",
    parent_code: "52",
    path_with_type: "Huyện Phù Cát, Tỉnh Bình Định",
  },
  {
    name: "An Nhơn",
    code: "549",
    parent_code: "52",
    path_with_type: "Thị xã An Nhơn, Tỉnh Bình Định",
  },
  {
    name: "Tuy Phước",
    code: "550",
    parent_code: "52",
    path_with_type: "Huyện Tuy Phước, Tỉnh Bình Định",
  },
  {
    name: "Vân Canh",
    code: "551",
    parent_code: "52",
    path_with_type: "Huyện Vân Canh, Tỉnh Bình Định",
  },
  {
    name: "Tuy Hoà",
    code: "555",
    parent_code: "54",
    path_with_type: "Thành phố Tuy Hoà, Tỉnh Phú Yên",
  },
  {
    name: "Sông Cầu",
    code: "557",
    parent_code: "54",
    path_with_type: "Thị xã Sông Cầu, Tỉnh Phú Yên",
  },
  {
    name: "Đồng Xuân",
    code: "558",
    parent_code: "54",
    path_with_type: "Huyện Đồng Xuân, Tỉnh Phú Yên",
  },
  {
    name: "Tuy An",
    code: "559",
    parent_code: "54",
    path_with_type: "Huyện Tuy An, Tỉnh Phú Yên",
  },
  {
    name: "Sơn Hòa",
    code: "560",
    parent_code: "54",
    path_with_type: "Huyện Sơn Hòa, Tỉnh Phú Yên",
  },
  {
    name: "Sông Hinh",
    code: "561",
    parent_code: "54",
    path_with_type: "Huyện Sông Hinh, Tỉnh Phú Yên",
  },
  {
    name: "Tây Hoà",
    code: "562",
    parent_code: "54",
    path_with_type: "Huyện Tây Hoà, Tỉnh Phú Yên",
  },
  {
    name: "Phú Hoà",
    code: "563",
    parent_code: "54",
    path_with_type: "Huyện Phú Hoà, Tỉnh Phú Yên",
  },
  {
    name: "Đông Hòa",
    code: "564",
    parent_code: "54",
    path_with_type: "Huyện Đông Hòa, Tỉnh Phú Yên",
  },
  {
    name: "Nha Trang",
    code: "568",
    parent_code: "56",
    path_with_type: "Thành phố Nha Trang, Tỉnh Khánh Hòa",
  },
  {
    name: "Cam Ranh",
    code: "569",
    parent_code: "56",
    path_with_type: "Thành phố Cam Ranh, Tỉnh Khánh Hòa",
  },
  {
    name: "Cam Lâm",
    code: "570",
    parent_code: "56",
    path_with_type: "Huyện Cam Lâm, Tỉnh Khánh Hòa",
  },
  {
    name: "Vạn Ninh",
    code: "571",
    parent_code: "56",
    path_with_type: "Huyện Vạn Ninh, Tỉnh Khánh Hòa",
  },
  {
    name: "Ninh Hòa",
    code: "572",
    parent_code: "56",
    path_with_type: "Thị xã Ninh Hòa, Tỉnh Khánh Hòa",
  },
  {
    name: "Khánh Vĩnh",
    code: "573",
    parent_code: "56",
    path_with_type: "Huyện Khánh Vĩnh, Tỉnh Khánh Hòa",
  },
  {
    name: "Diên Khánh",
    code: "574",
    parent_code: "56",
    path_with_type: "Huyện Diên Khánh, Tỉnh Khánh Hòa",
  },
  {
    name: "Khánh Sơn",
    code: "575",
    parent_code: "56",
    path_with_type: "Huyện Khánh Sơn, Tỉnh Khánh Hòa",
  },
  {
    name: "Trường Sa",
    code: "576",
    parent_code: "56",
    path_with_type: "Huyện Trường Sa, Tỉnh Khánh Hòa",
  },
  {
    name: "Phan Rang-Tháp Chàm",
    code: "582",
    parent_code: "58",
    path_with_type: "Thành phố Phan Rang-Tháp Chàm, Tỉnh Ninh Thuận",
  },
  {
    name: "Bác Ái",
    code: "584",
    parent_code: "58",
    path_with_type: "Huyện Bác Ái, Tỉnh Ninh Thuận",
  },
  {
    name: "Ninh Sơn",
    code: "585",
    parent_code: "58",
    path_with_type: "Huyện Ninh Sơn, Tỉnh Ninh Thuận",
  },
  {
    name: "Ninh Hải",
    code: "586",
    parent_code: "58",
    path_with_type: "Huyện Ninh Hải, Tỉnh Ninh Thuận",
  },
  {
    name: "Ninh Phước",
    code: "587",
    parent_code: "58",
    path_with_type: "Huyện Ninh Phước, Tỉnh Ninh Thuận",
  },
  {
    name: "Thuận Bắc",
    code: "588",
    parent_code: "58",
    path_with_type: "Huyện Thuận Bắc, Tỉnh Ninh Thuận",
  },
  {
    name: "Thuận Nam",
    code: "589",
    parent_code: "58",
    path_with_type: "Huyện Thuận Nam, Tỉnh Ninh Thuận",
  },
  {
    name: "Phan Thiết",
    code: "593",
    parent_code: "60",
    path_with_type: "Thành phố Phan Thiết, Tỉnh Bình Thuận",
  },
  {
    name: "La Gi",
    code: "594",
    parent_code: "60",
    path_with_type: "Thị xã La Gi, Tỉnh Bình Thuận",
  },
  {
    name: "Tuy Phong",
    code: "595",
    parent_code: "60",
    path_with_type: "Huyện Tuy Phong, Tỉnh Bình Thuận",
  },
  {
    name: "Bắc Bình",
    code: "596",
    parent_code: "60",
    path_with_type: "Huyện Bắc Bình, Tỉnh Bình Thuận",
  },
  {
    name: "Hàm Thuận Bắc",
    code: "597",
    parent_code: "60",
    path_with_type: "Huyện Hàm Thuận Bắc, Tỉnh Bình Thuận",
  },
  {
    name: "Hàm Thuận Nam",
    code: "598",
    parent_code: "60",
    path_with_type: "Huyện Hàm Thuận Nam, Tỉnh Bình Thuận",
  },
  {
    name: "Tánh Linh",
    code: "599",
    parent_code: "60",
    path_with_type: "Huyện Tánh Linh, Tỉnh Bình Thuận",
  },
  {
    name: "Đức Linh",
    code: "600",
    parent_code: "60",
    path_with_type: "Huyện Đức Linh, Tỉnh Bình Thuận",
  },
  {
    name: "Hàm Tân",
    code: "601",
    parent_code: "60",
    path_with_type: "Huyện Hàm Tân, Tỉnh Bình Thuận",
  },
  {
    name: "Phú Quí",
    code: "602",
    parent_code: "60",
    path_with_type: "Huyện Phú Quí, Tỉnh Bình Thuận",
  },
  {
    name: "Kon Tum",
    code: "608",
    parent_code: "62",
    path_with_type: "Thành phố Kon Tum, Tỉnh Kon Tum",
  },
  {
    name: "Đắk Glei",
    code: "610",
    parent_code: "62",
    path_with_type: "Huyện Đắk Glei, Tỉnh Kon Tum",
  },
  {
    name: "Ngọc Hồi",
    code: "611",
    parent_code: "62",
    path_with_type: "Huyện Ngọc Hồi, Tỉnh Kon Tum",
  },
  {
    name: "Đắk Tô",
    code: "612",
    parent_code: "62",
    path_with_type: "Huyện Đắk Tô, Tỉnh Kon Tum",
  },
  {
    name: "Kon Plông",
    code: "613",
    parent_code: "62",
    path_with_type: "Huyện Kon Plông, Tỉnh Kon Tum",
  },
  {
    name: "Kon Rẫy",
    code: "614",
    parent_code: "62",
    path_with_type: "Huyện Kon Rẫy, Tỉnh Kon Tum",
  },
  {
    name: "Đắk Hà",
    code: "615",
    parent_code: "62",
    path_with_type: "Huyện Đắk Hà, Tỉnh Kon Tum",
  },
  {
    name: "Sa Thầy",
    code: "616",
    parent_code: "62",
    path_with_type: "Huyện Sa Thầy, Tỉnh Kon Tum",
  },
  {
    name: "Tu Mơ Rông",
    code: "617",
    parent_code: "62",
    path_with_type: "Huyện Tu Mơ Rông, Tỉnh Kon Tum",
  },
  {
    name: "Ia H' Drai",
    code: "618",
    parent_code: "62",
    path_with_type: "Huyện Ia H' Drai, Tỉnh Kon Tum",
  },
  {
    name: "Pleiku",
    code: "622",
    parent_code: "64",
    path_with_type: "Thành phố Pleiku, Tỉnh Gia Lai",
  },
  {
    name: "An Khê",
    code: "623",
    parent_code: "64",
    path_with_type: "Thị xã An Khê, Tỉnh Gia Lai",
  },
  {
    name: "Ayun Pa",
    code: "624",
    parent_code: "64",
    path_with_type: "Thị xã Ayun Pa, Tỉnh Gia Lai",
  },
  {
    name: "KBang",
    code: "625",
    parent_code: "64",
    path_with_type: "Huyện KBang, Tỉnh Gia Lai",
  },
  {
    name: "Đăk Đoa",
    code: "626",
    parent_code: "64",
    path_with_type: "Huyện Đăk Đoa, Tỉnh Gia Lai",
  },
  {
    name: "Chư Păh",
    code: "627",
    parent_code: "64",
    path_with_type: "Huyện Chư Păh, Tỉnh Gia Lai",
  },
  {
    name: "Ia Grai",
    code: "628",
    parent_code: "64",
    path_with_type: "Huyện Ia Grai, Tỉnh Gia Lai",
  },
  {
    name: "Mang Yang",
    code: "629",
    parent_code: "64",
    path_with_type: "Huyện Mang Yang, Tỉnh Gia Lai",
  },
  {
    name: "Kông Chro",
    code: "630",
    parent_code: "64",
    path_with_type: "Huyện Kông Chro, Tỉnh Gia Lai",
  },
  {
    name: "Đức Cơ",
    code: "631",
    parent_code: "64",
    path_with_type: "Huyện Đức Cơ, Tỉnh Gia Lai",
  },
  {
    name: "Chư Prông",
    code: "632",
    parent_code: "64",
    path_with_type: "Huyện Chư Prông, Tỉnh Gia Lai",
  },
  {
    name: "Chư Sê",
    code: "633",
    parent_code: "64",
    path_with_type: "Huyện Chư Sê, Tỉnh Gia Lai",
  },
  {
    name: "Đăk Pơ",
    code: "634",
    parent_code: "64",
    path_with_type: "Huyện Đăk Pơ, Tỉnh Gia Lai",
  },
  {
    name: "Ia Pa",
    code: "635",
    parent_code: "64",
    path_with_type: "Huyện Ia Pa, Tỉnh Gia Lai",
  },
  {
    name: "Krông Pa",
    code: "637",
    parent_code: "64",
    path_with_type: "Huyện Krông Pa, Tỉnh Gia Lai",
  },
  {
    name: "Phú Thiện",
    code: "638",
    parent_code: "64",
    path_with_type: "Huyện Phú Thiện, Tỉnh Gia Lai",
  },
  {
    name: "Chư Pưh",
    code: "639",
    parent_code: "64",
    path_with_type: "Huyện Chư Pưh, Tỉnh Gia Lai",
  },
  {
    name: "Buôn Ma Thuột",
    code: "643",
    parent_code: "66",
    path_with_type: "Thành phố Buôn Ma Thuột, Tỉnh Đắk Lắk",
  },
  {
    name: "Buôn Hồ",
    code: "644",
    parent_code: "66",
    path_with_type: "Thị xã Buôn Hồ, Tỉnh Đắk Lắk",
  },
  {
    name: "Ea H'leo",
    code: "645",
    parent_code: "66",
    path_with_type: "Huyện Ea H'leo, Tỉnh Đắk Lắk",
  },
  {
    name: "Ea Súp",
    code: "646",
    parent_code: "66",
    path_with_type: "Huyện Ea Súp, Tỉnh Đắk Lắk",
  },
  {
    name: "Buôn Đôn",
    code: "647",
    parent_code: "66",
    path_with_type: "Huyện Buôn Đôn, Tỉnh Đắk Lắk",
  },
  {
    name: "Cư M'gar",
    code: "648",
    parent_code: "66",
    path_with_type: "Huyện Cư M'gar, Tỉnh Đắk Lắk",
  },
  {
    name: "Krông Búk",
    code: "649",
    parent_code: "66",
    path_with_type: "Huyện Krông Búk, Tỉnh Đắk Lắk",
  },
  {
    name: "Krông Năng",
    code: "650",
    parent_code: "66",
    path_with_type: "Huyện Krông Năng, Tỉnh Đắk Lắk",
  },
  {
    name: "Ea Kar",
    code: "651",
    parent_code: "66",
    path_with_type: "Huyện Ea Kar, Tỉnh Đắk Lắk",
  },
  {
    name: "M'Đrắk",
    code: "652",
    parent_code: "66",
    path_with_type: "Huyện M'Đrắk, Tỉnh Đắk Lắk",
  },
  {
    name: "Krông Bông",
    code: "653",
    parent_code: "66",
    path_with_type: "Huyện Krông Bông, Tỉnh Đắk Lắk",
  },
  {
    name: "Krông Pắc",
    code: "654",
    parent_code: "66",
    path_with_type: "Huyện Krông Pắc, Tỉnh Đắk Lắk",
  },
  {
    name: "Krông A Na",
    code: "655",
    parent_code: "66",
    path_with_type: "Huyện Krông A Na, Tỉnh Đắk Lắk",
  },
  {
    name: "Lắk",
    code: "656",
    parent_code: "66",
    path_with_type: "Huyện Lắk, Tỉnh Đắk Lắk",
  },
  {
    name: "Cư Kuin",
    code: "657",
    parent_code: "66",
    path_with_type: "Huyện Cư Kuin, Tỉnh Đắk Lắk",
  },
  {
    name: "Gia Nghĩa",
    code: "660",
    parent_code: "67",
    path_with_type: "Thị xã Gia Nghĩa, Tỉnh Đắk Nông",
  },
  {
    name: "Đăk Glong",
    code: "661",
    parent_code: "67",
    path_with_type: "Huyện Đăk Glong, Tỉnh Đắk Nông",
  },
  {
    name: "Cư Jút",
    code: "662",
    parent_code: "67",
    path_with_type: "Huyện Cư Jút, Tỉnh Đắk Nông",
  },
  {
    name: "Đắk Mil",
    code: "663",
    parent_code: "67",
    path_with_type: "Huyện Đắk Mil, Tỉnh Đắk Nông",
  },
  {
    name: "Krông Nô",
    code: "664",
    parent_code: "67",
    path_with_type: "Huyện Krông Nô, Tỉnh Đắk Nông",
  },
  {
    name: "Đắk Song",
    code: "665",
    parent_code: "67",
    path_with_type: "Huyện Đắk Song, Tỉnh Đắk Nông",
  },
  {
    name: "Đắk R'Lấp",
    code: "666",
    parent_code: "67",
    path_with_type: "Huyện Đắk R'Lấp, Tỉnh Đắk Nông",
  },
  {
    name: "Tuy Đức",
    code: "667",
    parent_code: "67",
    path_with_type: "Huyện Tuy Đức, Tỉnh Đắk Nông",
  },
  {
    name: "Đà Lạt",
    code: "672",
    parent_code: "68",
    path_with_type: "Thành phố Đà Lạt, Tỉnh Lâm Đồng",
  },
  {
    name: "Bảo Lộc",
    code: "673",
    parent_code: "68",
    path_with_type: "Thành phố Bảo Lộc, Tỉnh Lâm Đồng",
  },
  {
    name: "Đam Rông",
    code: "674",
    parent_code: "68",
    path_with_type: "Huyện Đam Rông, Tỉnh Lâm Đồng",
  },
  {
    name: "Lạc Dương",
    code: "675",
    parent_code: "68",
    path_with_type: "Huyện Lạc Dương, Tỉnh Lâm Đồng",
  },
  {
    name: "Lâm Hà",
    code: "676",
    parent_code: "68",
    path_with_type: "Huyện Lâm Hà, Tỉnh Lâm Đồng",
  },
  {
    name: "Đơn Dương",
    code: "677",
    parent_code: "68",
    path_with_type: "Huyện Đơn Dương, Tỉnh Lâm Đồng",
  },
  {
    name: "Đức Trọng",
    code: "678",
    parent_code: "68",
    path_with_type: "Huyện Đức Trọng, Tỉnh Lâm Đồng",
  },
  {
    name: "Di Linh",
    code: "679",
    parent_code: "68",
    path_with_type: "Huyện Di Linh, Tỉnh Lâm Đồng",
  },
  {
    name: "Bảo Lâm",
    code: "680",
    parent_code: "68",
    path_with_type: "Huyện Bảo Lâm, Tỉnh Lâm Đồng",
  },
  {
    name: "Đạ Huoai",
    code: "681",
    parent_code: "68",
    path_with_type: "Huyện Đạ Huoai, Tỉnh Lâm Đồng",
  },
  {
    name: "Đạ Tẻh",
    code: "682",
    parent_code: "68",
    path_with_type: "Huyện Đạ Tẻh, Tỉnh Lâm Đồng",
  },
  {
    name: "Cát Tiên",
    code: "683",
    parent_code: "68",
    path_with_type: "Huyện Cát Tiên, Tỉnh Lâm Đồng",
  },
  {
    name: "Phước Long",
    code: "688",
    parent_code: "70",
    path_with_type: "Thị xã Phước Long, Tỉnh Bình Phước",
  },
  {
    name: "Đồng Xoài",
    code: "689",
    parent_code: "70",
    path_with_type: "Thị xã Đồng Xoài, Tỉnh Bình Phước",
  },
  {
    name: "Bình Long",
    code: "690",
    parent_code: "70",
    path_with_type: "Thị xã Bình Long, Tỉnh Bình Phước",
  },
  {
    name: "Bù Gia Mập",
    code: "691",
    parent_code: "70",
    path_with_type: "Huyện Bù Gia Mập, Tỉnh Bình Phước",
  },
  {
    name: "Lộc Ninh",
    code: "692",
    parent_code: "70",
    path_with_type: "Huyện Lộc Ninh, Tỉnh Bình Phước",
  },
  {
    name: "Bù Đốp",
    code: "693",
    parent_code: "70",
    path_with_type: "Huyện Bù Đốp, Tỉnh Bình Phước",
  },
  {
    name: "Hớn Quản",
    code: "694",
    parent_code: "70",
    path_with_type: "Huyện Hớn Quản, Tỉnh Bình Phước",
  },
  {
    name: "Đồng Phú",
    code: "695",
    parent_code: "70",
    path_with_type: "Huyện Đồng Phú, Tỉnh Bình Phước",
  },
  {
    name: "Bù Đăng",
    code: "696",
    parent_code: "70",
    path_with_type: "Huyện Bù Đăng, Tỉnh Bình Phước",
  },
  {
    name: "Chơn Thành",
    code: "697",
    parent_code: "70",
    path_with_type: "Huyện Chơn Thành, Tỉnh Bình Phước",
  },
  {
    name: "Phú Riềng",
    code: "698",
    parent_code: "70",
    path_with_type: "Huyện Phú Riềng, Tỉnh Bình Phước",
  },
  {
    name: "Tây Ninh",
    code: "703",
    parent_code: "72",
    path_with_type: "Thành phố Tây Ninh, Tỉnh Tây Ninh",
  },
  {
    name: "Tân Biên",
    code: "705",
    parent_code: "72",
    path_with_type: "Huyện Tân Biên, Tỉnh Tây Ninh",
  },
  {
    name: "Tân Châu",
    code: "706",
    parent_code: "72",
    path_with_type: "Huyện Tân Châu, Tỉnh Tây Ninh",
  },
  {
    name: "Dương Minh Châu",
    code: "707",
    parent_code: "72",
    path_with_type: "Huyện Dương Minh Châu, Tỉnh Tây Ninh",
  },
  {
    name: "Châu Thành",
    code: "708",
    parent_code: "72",
    path_with_type: "Huyện Châu Thành, Tỉnh Tây Ninh",
  },
  {
    name: "Hòa Thành",
    code: "709",
    parent_code: "72",
    path_with_type: "Huyện Hòa Thành, Tỉnh Tây Ninh",
  },
  {
    name: "Gò Dầu",
    code: "710",
    parent_code: "72",
    path_with_type: "Huyện Gò Dầu, Tỉnh Tây Ninh",
  },
  {
    name: "Bến Cầu",
    code: "711",
    parent_code: "72",
    path_with_type: "Huyện Bến Cầu, Tỉnh Tây Ninh",
  },
  {
    name: "Trảng Bàng",
    code: "712",
    parent_code: "72",
    path_with_type: "Huyện Trảng Bàng, Tỉnh Tây Ninh",
  },
  {
    name: "Thủ Dầu Một",
    code: "718",
    parent_code: "74",
    path_with_type: "Thành phố Thủ Dầu Một, Tỉnh Bình Dương",
  },
  {
    name: "Bàu Bàng",
    code: "719",
    parent_code: "74",
    path_with_type: "Huyện Bàu Bàng, Tỉnh Bình Dương",
  },
  {
    name: "Dầu Tiếng",
    code: "720",
    parent_code: "74",
    path_with_type: "Huyện Dầu Tiếng, Tỉnh Bình Dương",
  },
  {
    name: "Bến Cát",
    code: "721",
    parent_code: "74",
    path_with_type: "Thị xã Bến Cát, Tỉnh Bình Dương",
  },
  {
    name: "Phú Giáo",
    code: "722",
    parent_code: "74",
    path_with_type: "Huyện Phú Giáo, Tỉnh Bình Dương",
  },
  {
    name: "Tân Uyên",
    code: "723",
    parent_code: "74",
    path_with_type: "Thị xã Tân Uyên, Tỉnh Bình Dương",
  },
  {
    name: "Dĩ An",
    code: "724",
    parent_code: "74",
    path_with_type: "Thị xã Dĩ An, Tỉnh Bình Dương",
  },
  {
    name: "Thuận An",
    code: "725",
    parent_code: "74",
    path_with_type: "Thị xã Thuận An, Tỉnh Bình Dương",
  },
  {
    name: "Bắc Tân Uyên",
    code: "726",
    parent_code: "74",
    path_with_type: "Huyện Bắc Tân Uyên, Tỉnh Bình Dương",
  },
  {
    name: "Biên Hòa",
    code: "731",
    parent_code: "75",
    path_with_type: "Thành phố Biên Hòa, Tỉnh Đồng Nai",
  },
  {
    name: "Long Khánh",
    code: "732",
    parent_code: "75",
    path_with_type: "Thị xã Long Khánh, Tỉnh Đồng Nai",
  },
  {
    name: "Tân Phú",
    code: "734",
    parent_code: "75",
    path_with_type: "Huyện Tân Phú, Tỉnh Đồng Nai",
  },
  {
    name: "Vĩnh Cửu",
    code: "735",
    parent_code: "75",
    path_with_type: "Huyện Vĩnh Cửu, Tỉnh Đồng Nai",
  },
  {
    name: "Định Quán",
    code: "736",
    parent_code: "75",
    path_with_type: "Huyện Định Quán, Tỉnh Đồng Nai",
  },
  {
    name: "Trảng Bom",
    code: "737",
    parent_code: "75",
    path_with_type: "Huyện Trảng Bom, Tỉnh Đồng Nai",
  },
  {
    name: "Thống Nhất",
    code: "738",
    parent_code: "75",
    path_with_type: "Huyện Thống Nhất, Tỉnh Đồng Nai",
  },
  {
    name: "Cẩm Mỹ",
    code: "739",
    parent_code: "75",
    path_with_type: "Huyện Cẩm Mỹ, Tỉnh Đồng Nai",
  },
  {
    name: "Long Thành",
    code: "740",
    parent_code: "75",
    path_with_type: "Huyện Long Thành, Tỉnh Đồng Nai",
  },
  {
    name: "Xuân Lộc",
    code: "741",
    parent_code: "75",
    path_with_type: "Huyện Xuân Lộc, Tỉnh Đồng Nai",
  },
  {
    name: "Nhơn Trạch",
    code: "742",
    parent_code: "75",
    path_with_type: "Huyện Nhơn Trạch, Tỉnh Đồng Nai",
  },
  {
    name: "Vũng Tàu",
    code: "747",
    parent_code: "77",
    path_with_type: "Thành phố Vũng Tàu, Tỉnh Bà Rịa - Vũng Tàu",
  },
  {
    name: "Bà Rịa",
    code: "748",
    parent_code: "77",
    path_with_type: "Thành phố Bà Rịa, Tỉnh Bà Rịa - Vũng Tàu",
  },
  {
    name: "Châu Đức",
    code: "750",
    parent_code: "77",
    path_with_type: "Huyện Châu Đức, Tỉnh Bà Rịa - Vũng Tàu",
  },
  {
    name: "Xuyên Mộc",
    code: "751",
    parent_code: "77",
    path_with_type: "Huyện Xuyên Mộc, Tỉnh Bà Rịa - Vũng Tàu",
  },
  {
    name: "Long Điền",
    code: "752",
    parent_code: "77",
    path_with_type: "Huyện Long Điền, Tỉnh Bà Rịa - Vũng Tàu",
  },
  {
    name: "Đất Đỏ",
    code: "753",
    parent_code: "77",
    path_with_type: "Huyện Đất Đỏ, Tỉnh Bà Rịa - Vũng Tàu",
  },
  {
    name: "Tân Thành",
    code: "754",
    parent_code: "77",
    path_with_type: "Huyện Tân Thành, Tỉnh Bà Rịa - Vũng Tàu",
  },
  {
    name: "1",
    code: "760",
    parent_code: "79",
    path_with_type: "Quận 1, Thành phố Hồ Chí Minh",
  },
  {
    name: "12",
    code: "761",
    parent_code: "79",
    path_with_type: "Quận 12, Thành phố Hồ Chí Minh",
  },
  {
    name: "Thủ Đức",
    code: "762",
    parent_code: "79",
    path_with_type: "Quận Thủ Đức, Thành phố Hồ Chí Minh",
  },
  {
    name: "9",
    code: "763",
    parent_code: "79",
    path_with_type: "Quận 9, Thành phố Hồ Chí Minh",
  },
  {
    name: "Gò Vấp",
    code: "764",
    parent_code: "79",
    path_with_type: "Quận Gò Vấp, Thành phố Hồ Chí Minh",
  },
  {
    name: "Bình Thạnh",
    code: "765",
    parent_code: "79",
    path_with_type: "Quận Bình Thạnh, Thành phố Hồ Chí Minh",
  },
  {
    name: "Tân Bình",
    code: "766",
    parent_code: "79",
    path_with_type: "Quận Tân Bình, Thành phố Hồ Chí Minh",
  },
  {
    name: "Tân Phú",
    code: "767",
    parent_code: "79",
    path_with_type: "Quận Tân Phú, Thành phố Hồ Chí Minh",
  },
  {
    name: "Phú Nhuận",
    code: "768",
    parent_code: "79",
    path_with_type: "Quận Phú Nhuận, Thành phố Hồ Chí Minh",
  },
  {
    name: "2",
    code: "769",
    parent_code: "79",
    path_with_type: "Quận 2, Thành phố Hồ Chí Minh",
  },
  {
    name: "3",
    code: "770",
    parent_code: "79",
    path_with_type: "Quận 3, Thành phố Hồ Chí Minh",
  },
  {
    name: "10",
    code: "771",
    parent_code: "79",
    path_with_type: "Quận 10, Thành phố Hồ Chí Minh",
  },
  {
    name: "11",
    code: "772",
    parent_code: "79",
    path_with_type: "Quận 11, Thành phố Hồ Chí Minh",
  },
  {
    name: "4",
    code: "773",
    parent_code: "79",
    path_with_type: "Quận 4, Thành phố Hồ Chí Minh",
  },
  {
    name: "5",
    code: "774",
    parent_code: "79",
    path_with_type: "Quận 5, Thành phố Hồ Chí Minh",
  },
  {
    name: "6",
    code: "775",
    parent_code: "79",
    path_with_type: "Quận 6, Thành phố Hồ Chí Minh",
  },
  {
    name: "8",
    code: "776",
    parent_code: "79",
    path_with_type: "Quận 8, Thành phố Hồ Chí Minh",
  },
  {
    name: "Bình Tân",
    code: "777",
    parent_code: "79",
    path_with_type: "Quận Bình Tân, Thành phố Hồ Chí Minh",
  },
  {
    name: "7",
    code: "778",
    parent_code: "79",
    path_with_type: "Quận 7, Thành phố Hồ Chí Minh",
  },
  {
    name: "Củ Chi",
    code: "783",
    parent_code: "79",
    path_with_type: "Huyện Củ Chi, Thành phố Hồ Chí Minh",
  },
  {
    name: "Hóc Môn",
    code: "784",
    parent_code: "79",
    path_with_type: "Huyện Hóc Môn, Thành phố Hồ Chí Minh",
  },
  {
    name: "Bình Chánh",
    code: "785",
    parent_code: "79",
    path_with_type: "Huyện Bình Chánh, Thành phố Hồ Chí Minh",
  },
  {
    name: "Nhà Bè",
    code: "786",
    parent_code: "79",
    path_with_type: "Huyện Nhà Bè, Thành phố Hồ Chí Minh",
  },
  {
    name: "Cần Giờ",
    code: "787",
    parent_code: "79",
    path_with_type: "Huyện Cần Giờ, Thành phố Hồ Chí Minh",
  },
  {
    name: "Tân An",
    code: "794",
    parent_code: "80",
    path_with_type: "Thành phố Tân An, Tỉnh Long An",
  },
  {
    name: "Kiến Tường",
    code: "795",
    parent_code: "80",
    path_with_type: "Thị xã Kiến Tường, Tỉnh Long An",
  },
  {
    name: "Tân Hưng",
    code: "796",
    parent_code: "80",
    path_with_type: "Huyện Tân Hưng, Tỉnh Long An",
  },
  {
    name: "Vĩnh Hưng",
    code: "797",
    parent_code: "80",
    path_with_type: "Huyện Vĩnh Hưng, Tỉnh Long An",
  },
  {
    name: "Mộc Hóa",
    code: "798",
    parent_code: "80",
    path_with_type: "Huyện Mộc Hóa, Tỉnh Long An",
  },
  {
    name: "Tân Thạnh",
    code: "799",
    parent_code: "80",
    path_with_type: "Huyện Tân Thạnh, Tỉnh Long An",
  },
  {
    name: "Thạnh Hóa",
    code: "800",
    parent_code: "80",
    path_with_type: "Huyện Thạnh Hóa, Tỉnh Long An",
  },
  {
    name: "Đức Huệ",
    code: "801",
    parent_code: "80",
    path_with_type: "Huyện Đức Huệ, Tỉnh Long An",
  },
  {
    name: "Đức Hòa",
    code: "802",
    parent_code: "80",
    path_with_type: "Huyện Đức Hòa, Tỉnh Long An",
  },
  {
    name: "Bến Lức",
    code: "803",
    parent_code: "80",
    path_with_type: "Huyện Bến Lức, Tỉnh Long An",
  },
  {
    name: "Thủ Thừa",
    code: "804",
    parent_code: "80",
    path_with_type: "Huyện Thủ Thừa, Tỉnh Long An",
  },
  {
    name: "Tân Trụ",
    code: "805",
    parent_code: "80",
    path_with_type: "Huyện Tân Trụ, Tỉnh Long An",
  },
  {
    name: "Cần Đước",
    code: "806",
    parent_code: "80",
    path_with_type: "Huyện Cần Đước, Tỉnh Long An",
  },
  {
    name: "Cần Giuộc",
    code: "807",
    parent_code: "80",
    path_with_type: "Huyện Cần Giuộc, Tỉnh Long An",
  },
  {
    name: "Châu Thành",
    code: "808",
    parent_code: "80",
    path_with_type: "Huyện Châu Thành, Tỉnh Long An",
  },
  {
    name: "Mỹ Tho",
    code: "815",
    parent_code: "82",
    path_with_type: "Thành phố Mỹ Tho, Tỉnh Tiền Giang",
  },
  {
    name: "Gò Công",
    code: "816",
    parent_code: "82",
    path_with_type: "Thị xã Gò Công, Tỉnh Tiền Giang",
  },
  {
    name: "Cai Lậy",
    code: "817",
    parent_code: "82",
    path_with_type: "Thị xã Cai Lậy, Tỉnh Tiền Giang",
  },
  {
    name: "Tân Phước",
    code: "818",
    parent_code: "82",
    path_with_type: "Huyện Tân Phước, Tỉnh Tiền Giang",
  },
  {
    name: "Cái Bè",
    code: "819",
    parent_code: "82",
    path_with_type: "Huyện Cái Bè, Tỉnh Tiền Giang",
  },
  {
    name: "Cai Lậy",
    code: "820",
    parent_code: "82",
    path_with_type: "Huyện Cai Lậy, Tỉnh Tiền Giang",
  },
  {
    name: "Châu Thành",
    code: "821",
    parent_code: "82",
    path_with_type: "Huyện Châu Thành, Tỉnh Tiền Giang",
  },
  {
    name: "Chợ Gạo",
    code: "822",
    parent_code: "82",
    path_with_type: "Huyện Chợ Gạo, Tỉnh Tiền Giang",
  },
  {
    name: "Gò Công Tây",
    code: "823",
    parent_code: "82",
    path_with_type: "Huyện Gò Công Tây, Tỉnh Tiền Giang",
  },
  {
    name: "Gò Công Đông",
    code: "824",
    parent_code: "82",
    path_with_type: "Huyện Gò Công Đông, Tỉnh Tiền Giang",
  },
  {
    name: "Tân Phú Đông",
    code: "825",
    parent_code: "82",
    path_with_type: "Huyện Tân Phú Đông, Tỉnh Tiền Giang",
  },
  {
    name: "Bến Tre",
    code: "829",
    parent_code: "83",
    path_with_type: "Thành phố Bến Tre, Tỉnh Bến Tre",
  },
  {
    name: "Châu Thành",
    code: "831",
    parent_code: "83",
    path_with_type: "Huyện Châu Thành, Tỉnh Bến Tre",
  },
  {
    name: "Chợ Lách",
    code: "832",
    parent_code: "83",
    path_with_type: "Huyện Chợ Lách, Tỉnh Bến Tre",
  },
  {
    name: "Mỏ Cày Nam",
    code: "833",
    parent_code: "83",
    path_with_type: "Huyện Mỏ Cày Nam, Tỉnh Bến Tre",
  },
  {
    name: "Giồng Trôm",
    code: "834",
    parent_code: "83",
    path_with_type: "Huyện Giồng Trôm, Tỉnh Bến Tre",
  },
  {
    name: "Bình Đại",
    code: "835",
    parent_code: "83",
    path_with_type: "Huyện Bình Đại, Tỉnh Bến Tre",
  },
  {
    name: "Ba Tri",
    code: "836",
    parent_code: "83",
    path_with_type: "Huyện Ba Tri, Tỉnh Bến Tre",
  },
  {
    name: "Thạnh Phú",
    code: "837",
    parent_code: "83",
    path_with_type: "Huyện Thạnh Phú, Tỉnh Bến Tre",
  },
  {
    name: "Mỏ Cày Bắc",
    code: "838",
    parent_code: "83",
    path_with_type: "Huyện Mỏ Cày Bắc, Tỉnh Bến Tre",
  },
  {
    name: "Trà Vinh",
    code: "842",
    parent_code: "84",
    path_with_type: "Thành phố Trà Vinh, Tỉnh Trà Vinh",
  },
  {
    name: "Càng Long",
    code: "844",
    parent_code: "84",
    path_with_type: "Huyện Càng Long, Tỉnh Trà Vinh",
  },
  {
    name: "Cầu Kè",
    code: "845",
    parent_code: "84",
    path_with_type: "Huyện Cầu Kè, Tỉnh Trà Vinh",
  },
  {
    name: "Tiểu Cần",
    code: "846",
    parent_code: "84",
    path_with_type: "Huyện Tiểu Cần, Tỉnh Trà Vinh",
  },
  {
    name: "Châu Thành",
    code: "847",
    parent_code: "84",
    path_with_type: "Huyện Châu Thành, Tỉnh Trà Vinh",
  },
  {
    name: "Cầu Ngang",
    code: "848",
    parent_code: "84",
    path_with_type: "Huyện Cầu Ngang, Tỉnh Trà Vinh",
  },
  {
    name: "Trà Cú",
    code: "849",
    parent_code: "84",
    path_with_type: "Huyện Trà Cú, Tỉnh Trà Vinh",
  },
  {
    name: "Duyên Hải",
    code: "850",
    parent_code: "84",
    path_with_type: "Huyện Duyên Hải, Tỉnh Trà Vinh",
  },
  {
    name: "Duyên Hải",
    code: "851",
    parent_code: "84",
    path_with_type: "Thị xã Duyên Hải, Tỉnh Trà Vinh",
  },
  {
    name: "Vĩnh Long",
    code: "855",
    parent_code: "86",
    path_with_type: "Thành phố Vĩnh Long, Tỉnh Vĩnh Long",
  },
  {
    name: "Long Hồ",
    code: "857",
    parent_code: "86",
    path_with_type: "Huyện Long Hồ, Tỉnh Vĩnh Long",
  },
  {
    name: "Mang Thít",
    code: "858",
    parent_code: "86",
    path_with_type: "Huyện Mang Thít, Tỉnh Vĩnh Long",
  },
  {
    name: "Vũng Liêm",
    code: "859",
    parent_code: "86",
    path_with_type: "Huyện  Vũng Liêm, Tỉnh Vĩnh Long",
  },
  {
    name: "Tam Bình",
    code: "860",
    parent_code: "86",
    path_with_type: "Huyện Tam Bình, Tỉnh Vĩnh Long",
  },
  {
    name: "Bình Minh",
    code: "861",
    parent_code: "86",
    path_with_type: "Thị xã Bình Minh, Tỉnh Vĩnh Long",
  },
  {
    name: "Trà Ôn",
    code: "862",
    parent_code: "86",
    path_with_type: "Huyện Trà Ôn, Tỉnh Vĩnh Long",
  },
  {
    name: "Bình Tân",
    code: "863",
    parent_code: "86",
    path_with_type: "Huyện Bình Tân, Tỉnh Vĩnh Long",
  },
  {
    name: "Cao Lãnh",
    code: "866",
    parent_code: "87",
    path_with_type: "Thành phố Cao Lãnh, Tỉnh Đồng Tháp",
  },
  {
    name: "Sa Đéc",
    code: "867",
    parent_code: "87",
    path_with_type: "Thành phố Sa Đéc, Tỉnh Đồng Tháp",
  },
  {
    name: "Hồng Ngự",
    code: "868",
    parent_code: "87",
    path_with_type: "Thị xã Hồng Ngự, Tỉnh Đồng Tháp",
  },
  {
    name: "Tân Hồng",
    code: "869",
    parent_code: "87",
    path_with_type: "Huyện Tân Hồng, Tỉnh Đồng Tháp",
  },
  {
    name: "Hồng Ngự",
    code: "870",
    parent_code: "87",
    path_with_type: "Huyện Hồng Ngự, Tỉnh Đồng Tháp",
  },
  {
    name: "Tam Nông",
    code: "871",
    parent_code: "87",
    path_with_type: "Huyện Tam Nông, Tỉnh Đồng Tháp",
  },
  {
    name: "Tháp Mười",
    code: "872",
    parent_code: "87",
    path_with_type: "Huyện Tháp Mười, Tỉnh Đồng Tháp",
  },
  {
    name: "Cao Lãnh",
    code: "873",
    parent_code: "87",
    path_with_type: "Huyện Cao Lãnh, Tỉnh Đồng Tháp",
  },
  {
    name: "Thanh Bình",
    code: "874",
    parent_code: "87",
    path_with_type: "Huyện Thanh Bình, Tỉnh Đồng Tháp",
  },
  {
    name: "Lấp Vò",
    code: "875",
    parent_code: "87",
    path_with_type: "Huyện Lấp Vò, Tỉnh Đồng Tháp",
  },
  {
    name: "Lai Vung",
    code: "876",
    parent_code: "87",
    path_with_type: "Huyện Lai Vung, Tỉnh Đồng Tháp",
  },
  {
    name: "Châu Thành",
    code: "877",
    parent_code: "87",
    path_with_type: "Huyện Châu Thành, Tỉnh Đồng Tháp",
  },
  {
    name: "Long Xuyên",
    code: "883",
    parent_code: "89",
    path_with_type: "Thành phố Long Xuyên, Tỉnh An Giang",
  },
  {
    name: "Châu Đốc",
    code: "884",
    parent_code: "89",
    path_with_type: "Thành phố Châu Đốc, Tỉnh An Giang",
  },
  {
    name: "An Phú",
    code: "886",
    parent_code: "89",
    path_with_type: "Huyện An Phú, Tỉnh An Giang",
  },
  {
    name: "Tân Châu",
    code: "887",
    parent_code: "89",
    path_with_type: "Thị xã Tân Châu, Tỉnh An Giang",
  },
  {
    name: "Phú Tân",
    code: "888",
    parent_code: "89",
    path_with_type: "Huyện Phú Tân, Tỉnh An Giang",
  },
  {
    name: "Châu Phú",
    code: "889",
    parent_code: "89",
    path_with_type: "Huyện Châu Phú, Tỉnh An Giang",
  },
  {
    name: "Tịnh Biên",
    code: "890",
    parent_code: "89",
    path_with_type: "Huyện Tịnh Biên, Tỉnh An Giang",
  },
  {
    name: "Tri Tôn",
    code: "891",
    parent_code: "89",
    path_with_type: "Huyện Tri Tôn, Tỉnh An Giang",
  },
  {
    name: "Châu Thành",
    code: "892",
    parent_code: "89",
    path_with_type: "Huyện Châu Thành, Tỉnh An Giang",
  },
  {
    name: "Chợ Mới",
    code: "893",
    parent_code: "89",
    path_with_type: "Huyện Chợ Mới, Tỉnh An Giang",
  },
  {
    name: "Thoại Sơn",
    code: "894",
    parent_code: "89",
    path_with_type: "Huyện Thoại Sơn, Tỉnh An Giang",
  },
  {
    name: "Rạch Giá",
    code: "899",
    parent_code: "91",
    path_with_type: "Thành phố Rạch Giá, Tỉnh Kiên Giang",
  },
  {
    name: "Hà Tiên",
    code: "900",
    parent_code: "91",
    path_with_type: "Thị xã Hà Tiên, Tỉnh Kiên Giang",
  },
  {
    name: "Kiên Lương",
    code: "902",
    parent_code: "91",
    path_with_type: "Huyện Kiên Lương, Tỉnh Kiên Giang",
  },
  {
    name: "Hòn Đất",
    code: "903",
    parent_code: "91",
    path_with_type: "Huyện Hòn Đất, Tỉnh Kiên Giang",
  },
  {
    name: "Tân Hiệp",
    code: "904",
    parent_code: "91",
    path_with_type: "Huyện Tân Hiệp, Tỉnh Kiên Giang",
  },
  {
    name: "Châu Thành",
    code: "905",
    parent_code: "91",
    path_with_type: "Huyện Châu Thành, Tỉnh Kiên Giang",
  },
  {
    name: "Giồng Riềng",
    code: "906",
    parent_code: "91",
    path_with_type: "Huyện Giồng Riềng, Tỉnh Kiên Giang",
  },
  {
    name: "Gò Quao",
    code: "907",
    parent_code: "91",
    path_with_type: "Huyện Gò Quao, Tỉnh Kiên Giang",
  },
  {
    name: "An Biên",
    code: "908",
    parent_code: "91",
    path_with_type: "Huyện An Biên, Tỉnh Kiên Giang",
  },
  {
    name: "An Minh",
    code: "909",
    parent_code: "91",
    path_with_type: "Huyện An Minh, Tỉnh Kiên Giang",
  },
  {
    name: "Vĩnh Thuận",
    code: "910",
    parent_code: "91",
    path_with_type: "Huyện Vĩnh Thuận, Tỉnh Kiên Giang",
  },
  {
    name: "Phú Quốc",
    code: "911",
    parent_code: "91",
    path_with_type: "Huyện Phú Quốc, Tỉnh Kiên Giang",
  },
  {
    name: "Kiên Hải",
    code: "912",
    parent_code: "91",
    path_with_type: "Huyện Kiên Hải, Tỉnh Kiên Giang",
  },
  {
    name: "U Minh Thượng",
    code: "913",
    parent_code: "91",
    path_with_type: "Huyện U Minh Thượng, Tỉnh Kiên Giang",
  },
  {
    name: "Giang Thành",
    code: "914",
    parent_code: "91",
    path_with_type: "Huyện Giang Thành, Tỉnh Kiên Giang",
  },
  {
    name: "Ninh Kiều",
    code: "916",
    parent_code: "92",
    path_with_type: "Quận Ninh Kiều, Thành phố Cần Thơ",
  },
  {
    name: "Ô Môn",
    code: "917",
    parent_code: "92",
    path_with_type: "Quận Ô Môn, Thành phố Cần Thơ",
  },
  {
    name: "Bình Thuỷ",
    code: "918",
    parent_code: "92",
    path_with_type: "Quận Bình Thuỷ, Thành phố Cần Thơ",
  },
  {
    name: "Cái Răng",
    code: "919",
    parent_code: "92",
    path_with_type: "Quận Cái Răng, Thành phố Cần Thơ",
  },
  {
    name: "Thốt Nốt",
    code: "923",
    parent_code: "92",
    path_with_type: "Quận Thốt Nốt, Thành phố Cần Thơ",
  },
  {
    name: "Vĩnh Thạnh",
    code: "924",
    parent_code: "92",
    path_with_type: "Huyện Vĩnh Thạnh, Thành phố Cần Thơ",
  },
  {
    name: "Cờ Đỏ",
    code: "925",
    parent_code: "92",
    path_with_type: "Huyện Cờ Đỏ, Thành phố Cần Thơ",
  },
  {
    name: "Phong Điền",
    code: "926",
    parent_code: "92",
    path_with_type: "Huyện Phong Điền, Thành phố Cần Thơ",
  },
  {
    name: "Thới Lai",
    code: "927",
    parent_code: "92",
    path_with_type: "Huyện Thới Lai, Thành phố Cần Thơ",
  },
  {
    name: "Vị Thanh",
    code: "930",
    parent_code: "93",
    path_with_type: "Thành phố Vị Thanh, Tỉnh Hậu Giang",
  },
  {
    name: "Ngã Bảy",
    code: "931",
    parent_code: "93",
    path_with_type: "Thị xã Ngã Bảy, Tỉnh Hậu Giang",
  },
  {
    name: "Châu Thành A",
    code: "932",
    parent_code: "93",
    path_with_type: "Huyện Châu Thành A, Tỉnh Hậu Giang",
  },
  {
    name: "Châu Thành",
    code: "933",
    parent_code: "93",
    path_with_type: "Huyện Châu Thành, Tỉnh Hậu Giang",
  },
  {
    name: "Phụng Hiệp",
    code: "934",
    parent_code: "93",
    path_with_type: "Huyện Phụng Hiệp, Tỉnh Hậu Giang",
  },
  {
    name: "Vị Thuỷ",
    code: "935",
    parent_code: "93",
    path_with_type: "Huyện Vị Thuỷ, Tỉnh Hậu Giang",
  },
  {
    name: "Long Mỹ",
    code: "936",
    parent_code: "93",
    path_with_type: "Huyện Long Mỹ, Tỉnh Hậu Giang",
  },
  {
    name: "Long Mỹ",
    code: "937",
    parent_code: "93",
    path_with_type: "Thị xã Long Mỹ, Tỉnh Hậu Giang",
  },
  {
    name: "Sóc Trăng",
    code: "941",
    parent_code: "94",
    path_with_type: "Thành phố Sóc Trăng, Tỉnh Sóc Trăng",
  },
  {
    name: "Châu Thành",
    code: "942",
    parent_code: "94",
    path_with_type: "Huyện Châu Thành, Tỉnh Sóc Trăng",
  },
  {
    name: "Kế Sách",
    code: "943",
    parent_code: "94",
    path_with_type: "Huyện Kế Sách, Tỉnh Sóc Trăng",
  },
  {
    name: "Mỹ Tú",
    code: "944",
    parent_code: "94",
    path_with_type: "Huyện Mỹ Tú, Tỉnh Sóc Trăng",
  },
  {
    name: "Cù Lao Dung",
    code: "945",
    parent_code: "94",
    path_with_type: "Huyện Cù Lao Dung, Tỉnh Sóc Trăng",
  },
  {
    name: "Long Phú",
    code: "946",
    parent_code: "94",
    path_with_type: "Huyện Long Phú, Tỉnh Sóc Trăng",
  },
  {
    name: "Mỹ Xuyên",
    code: "947",
    parent_code: "94",
    path_with_type: "Huyện Mỹ Xuyên, Tỉnh Sóc Trăng",
  },
  {
    name: "Ngã Năm",
    code: "948",
    parent_code: "94",
    path_with_type: "Thị xã Ngã Năm, Tỉnh Sóc Trăng",
  },
  {
    name: "Thạnh Trị",
    code: "949",
    parent_code: "94",
    path_with_type: "Huyện Thạnh Trị, Tỉnh Sóc Trăng",
  },
  {
    name: "Vĩnh Châu",
    code: "950",
    parent_code: "94",
    path_with_type: "Thị xã Vĩnh Châu, Tỉnh Sóc Trăng",
  },
  {
    name: "Trần Đề",
    code: "951",
    parent_code: "94",
    path_with_type: "Huyện Trần Đề, Tỉnh Sóc Trăng",
  },
  {
    name: "Bạc Liêu",
    code: "954",
    parent_code: "95",
    path_with_type: "Thành phố Bạc Liêu, Tỉnh Bạc Liêu",
  },
  {
    name: "Hồng Dân",
    code: "956",
    parent_code: "95",
    path_with_type: "Huyện Hồng Dân, Tỉnh Bạc Liêu",
  },
  {
    name: "Phước Long",
    code: "957",
    parent_code: "95",
    path_with_type: "Huyện Phước Long, Tỉnh Bạc Liêu",
  },
  {
    name: "Vĩnh Lợi",
    code: "958",
    parent_code: "95",
    path_with_type: "Huyện Vĩnh Lợi, Tỉnh Bạc Liêu",
  },
  {
    name: "Giá Rai",
    code: "959",
    parent_code: "95",
    path_with_type: "Thị xã Giá Rai, Tỉnh Bạc Liêu",
  },
  {
    name: "Đông Hải",
    code: "960",
    parent_code: "95",
    path_with_type: "Huyện Đông Hải, Tỉnh Bạc Liêu",
  },
  {
    name: "Hoà Bình",
    code: "961",
    parent_code: "95",
    path_with_type: "Huyện Hoà Bình, Tỉnh Bạc Liêu",
  },
  {
    name: "Cà Mau",
    code: "964",
    parent_code: "96",
    path_with_type: "Thành phố Cà Mau, Tỉnh Cà Mau",
  },
  {
    name: "U Minh",
    code: "966",
    parent_code: "96",
    path_with_type: "Huyện U Minh, Tỉnh Cà Mau",
  },
  {
    name: "Thới Bình",
    code: "967",
    parent_code: "96",
    path_with_type: "Huyện Thới Bình, Tỉnh Cà Mau",
  },
  {
    name: "Trần Văn Thời",
    code: "968",
    parent_code: "96",
    path_with_type: "Huyện Trần Văn Thời, Tỉnh Cà Mau",
  },
  {
    name: "Cái Nước",
    code: "969",
    parent_code: "96",
    path_with_type: "Huyện Cái Nước, Tỉnh Cà Mau",
  },
  {
    name: "Đầm Dơi",
    code: "970",
    parent_code: "96",
    path_with_type: "Huyện Đầm Dơi, Tỉnh Cà Mau",
  },
  {
    name: "Năm Căn",
    code: "971",
    parent_code: "96",
    path_with_type: "Huyện Năm Căn, Tỉnh Cà Mau",
  },
  {
    name: "Phú Tân",
    code: "972",
    parent_code: "96",
    path_with_type: "Huyện Phú Tân, Tỉnh Cà Mau",
  },
  {
    name: "Ngọc Hiển",
    code: "973",
    parent_code: "96",
    path_with_type: "Huyện Ngọc Hiển, Tỉnh Cà Mau",
  },
  {
    name: "Tuyên Quang",
    code: "070",
    parent_code: "08",
    path_with_type: "Thành phố Tuyên Quang, Tỉnh Tuyên Quang",
  },
  {
    name: "Lâm Bình",
    code: "071",
    parent_code: "08",
    path_with_type: "Huyện Lâm Bình, Tỉnh Tuyên Quang",
  },
  {
    name: "Nà Hang",
    code: "072",
    parent_code: "08",
    path_with_type: "Huyện Nà Hang, Tỉnh Tuyên Quang",
  },
  {
    name: "Chiêm Hóa",
    code: "073",
    parent_code: "08",
    path_with_type: "Huyện Chiêm Hóa, Tỉnh Tuyên Quang",
  },
  {
    name: "Hàm Yên",
    code: "074",
    parent_code: "08",
    path_with_type: "Huyện Hàm Yên, Tỉnh Tuyên Quang",
  },
  {
    name: "Yên Sơn",
    code: "075",
    parent_code: "08",
    path_with_type: "Huyện Yên Sơn, Tỉnh Tuyên Quang",
  },
  {
    name: "Sơn Dương",
    code: "076",
    parent_code: "08",
    path_with_type: "Huyện Sơn Dương, Tỉnh Tuyên Quang",
  },
  {
    name: "Ba Đình",
    code: "001",
    parent_code: "01",
    path_with_type: "Quận Ba Đình, Thành phố Hà Nội",
  },
  {
    name: "Hoàn Kiếm",
    code: "002",
    parent_code: "01",
    path_with_type: "Quận Hoàn Kiếm, Thành phố Hà Nội",
  },
  {
    name: "Tây Hồ",
    code: "003",
    parent_code: "01",
    path_with_type: "Quận Tây Hồ, Thành phố Hà Nội",
  },
  {
    name: "Long Biên",
    code: "004",
    parent_code: "01",
    path_with_type: "Quận Long Biên, Thành phố Hà Nội",
  },
  {
    name: "Cầu Giấy",
    code: "005",
    parent_code: "01",
    path_with_type: "Quận Cầu Giấy, Thành phố Hà Nội",
  },
  {
    name: "Đống Đa",
    code: "006",
    parent_code: "01",
    path_with_type: "Quận Đống Đa, Thành phố Hà Nội",
  },
  {
    name: "Hai Bà Trưng",
    code: "007",
    parent_code: "01",
    path_with_type: "Quận Hai Bà Trưng, Thành phố Hà Nội",
  },
  {
    name: "Hoàng Mai",
    code: "008",
    parent_code: "01",
    path_with_type: "Quận Hoàng Mai, Thành phố Hà Nội",
  },
  {
    name: "Thanh Xuân",
    code: "009",
    parent_code: "01",
    path_with_type: "Quận Thanh Xuân, Thành phố Hà Nội",
  },
  {
    name: "Sóc Sơn",
    code: "016",
    parent_code: "01",
    path_with_type: "Huyện Sóc Sơn, Thành phố Hà Nội",
  },
  {
    name: "Đông Anh",
    code: "017",
    parent_code: "01",
    path_with_type: "Huyện Đông Anh, Thành phố Hà Nội",
  },
  {
    name: "Gia Lâm",
    code: "018",
    parent_code: "01",
    path_with_type: "Huyện Gia Lâm, Thành phố Hà Nội",
  },
  {
    name: "Nam Từ Liêm",
    code: "019",
    parent_code: "01",
    path_with_type: "Quận Nam Từ Liêm, Thành phố Hà Nội",
  },
  {
    name: "Thanh Trì",
    code: "020",
    parent_code: "01",
    path_with_type: "Huyện Thanh Trì, Thành phố Hà Nội",
  },
  {
    name: "Bắc Từ Liêm",
    code: "021",
    parent_code: "01",
    path_with_type: "Quận Bắc Từ Liêm, Thành phố Hà Nội",
  },
  {
    name: "Lào Cai",
    code: "080",
    parent_code: "10",
    path_with_type: "Thành phố Lào Cai, Tỉnh Lào Cai",
  },
  {
    name: "Bát Xát",
    code: "082",
    parent_code: "10",
    path_with_type: "Huyện Bát Xát, Tỉnh Lào Cai",
  },
  {
    name: "Mường Khương",
    code: "083",
    parent_code: "10",
    path_with_type: "Huyện Mường Khương, Tỉnh Lào Cai",
  },
  {
    name: "Si Ma Cai",
    code: "084",
    parent_code: "10",
    path_with_type: "Huyện Si Ma Cai, Tỉnh Lào Cai",
  },
  {
    name: "Bắc Hà",
    code: "085",
    parent_code: "10",
    path_with_type: "Huyện Bắc Hà, Tỉnh Lào Cai",
  },
  {
    name: "Bảo Thắng",
    code: "086",
    parent_code: "10",
    path_with_type: "Huyện Bảo Thắng, Tỉnh Lào Cai",
  },
  {
    name: "Bảo Yên",
    code: "087",
    parent_code: "10",
    path_with_type: "Huyện Bảo Yên, Tỉnh Lào Cai",
  },
  {
    name: "Sa Pa",
    code: "088",
    parent_code: "10",
    path_with_type: "Huyện Sa Pa, Tỉnh Lào Cai",
  },
  {
    name: "Văn Bàn",
    code: "089",
    parent_code: "10",
    path_with_type: "Huyện Văn Bàn, Tỉnh Lào Cai",
  },
  {
    name: "Hà Giang",
    code: "024",
    parent_code: "02",
    path_with_type: "Thành phố Hà Giang, Tỉnh Hà Giang",
  },
  {
    name: "Đồng Văn",
    code: "026",
    parent_code: "02",
    path_with_type: "Huyện Đồng Văn, Tỉnh Hà Giang",
  },
  {
    name: "Mèo Vạc",
    code: "027",
    parent_code: "02",
    path_with_type: "Huyện Mèo Vạc, Tỉnh Hà Giang",
  },
  {
    name: "Yên Minh",
    code: "028",
    parent_code: "02",
    path_with_type: "Huyện Yên Minh, Tỉnh Hà Giang",
  },
  {
    name: "Quản Bạ",
    code: "029",
    parent_code: "02",
    path_with_type: "Huyện Quản Bạ, Tỉnh Hà Giang",
  },
  {
    name: "Vị Xuyên",
    code: "030",
    parent_code: "02",
    path_with_type: "Huyện Vị Xuyên, Tỉnh Hà Giang",
  },
  {
    name: "Bắc Mê",
    code: "031",
    parent_code: "02",
    path_with_type: "Huyện Bắc Mê, Tỉnh Hà Giang",
  },
  {
    name: "Hoàng Su Phì",
    code: "032",
    parent_code: "02",
    path_with_type: "Huyện Hoàng Su Phì, Tỉnh Hà Giang",
  },
  {
    name: "Xín Mần",
    code: "033",
    parent_code: "02",
    path_with_type: "Huyện Xín Mần, Tỉnh Hà Giang",
  },
  {
    name: "Bắc Quang",
    code: "034",
    parent_code: "02",
    path_with_type: "Huyện Bắc Quang, Tỉnh Hà Giang",
  },
  {
    name: "Quang Bình",
    code: "035",
    parent_code: "02",
    path_with_type: "Huyện Quang Bình, Tỉnh Hà Giang",
  },
  {
    name: "Cao Bằng",
    code: "040",
    parent_code: "04",
    path_with_type: "Thành phố Cao Bằng, Tỉnh Cao Bằng",
  },
  {
    name: "Bảo Lâm",
    code: "042",
    parent_code: "04",
    path_with_type: "Huyện Bảo Lâm, Tỉnh Cao Bằng",
  },
  {
    name: "Bảo Lạc",
    code: "043",
    parent_code: "04",
    path_with_type: "Huyện Bảo Lạc, Tỉnh Cao Bằng",
  },
  {
    name: "Thông Nông",
    code: "044",
    parent_code: "04",
    path_with_type: "Huyện Thông Nông, Tỉnh Cao Bằng",
  },
  {
    name: "Hà Quảng",
    code: "045",
    parent_code: "04",
    path_with_type: "Huyện Hà Quảng, Tỉnh Cao Bằng",
  },
  {
    name: "Trà Lĩnh",
    code: "046",
    parent_code: "04",
    path_with_type: "Huyện Trà Lĩnh, Tỉnh Cao Bằng",
  },
  {
    name: "Trùng Khánh",
    code: "047",
    parent_code: "04",
    path_with_type: "Huyện Trùng Khánh, Tỉnh Cao Bằng",
  },
  {
    name: "Hạ Lang",
    code: "048",
    parent_code: "04",
    path_with_type: "Huyện Hạ Lang, Tỉnh Cao Bằng",
  },
  {
    name: "Quảng Uyên",
    code: "049",
    parent_code: "04",
    path_with_type: "Huyện Quảng Uyên, Tỉnh Cao Bằng",
  },
  {
    name: "Phục Hoà",
    code: "050",
    parent_code: "04",
    path_with_type: "Huyện Phục Hoà, Tỉnh Cao Bằng",
  },
  {
    name: "Hoà An",
    code: "051",
    parent_code: "04",
    path_with_type: "Huyện Hoà An, Tỉnh Cao Bằng",
  },
  {
    name: "Nguyên Bình",
    code: "052",
    parent_code: "04",
    path_with_type: "Huyện Nguyên Bình, Tỉnh Cao Bằng",
  },
  {
    name: "Thạch An",
    code: "053",
    parent_code: "04",
    path_with_type: "Huyện Thạch An, Tỉnh Cao Bằng",
  },
  {
    name: "Điện Biên Phủ",
    code: "094",
    parent_code: "11",
    path_with_type: "Thành phố Điện Biên Phủ, Tỉnh Điện Biên",
  },
  {
    name: "Mường Lay",
    code: "095",
    parent_code: "11",
    path_with_type: "Thị xã Mường Lay, Tỉnh Điện Biên",
  },
  {
    name: "Mường Nhé",
    code: "096",
    parent_code: "11",
    path_with_type: "Huyện Mường Nhé, Tỉnh Điện Biên",
  },
  {
    name: "Mường Chà",
    code: "097",
    parent_code: "11",
    path_with_type: "Huyện Mường Chà, Tỉnh Điện Biên",
  },
  {
    name: "Tủa Chùa",
    code: "098",
    parent_code: "11",
    path_with_type: "Huyện Tủa Chùa, Tỉnh Điện Biên",
  },
  {
    name: "Tuần Giáo",
    code: "099",
    parent_code: "11",
    path_with_type: "Huyện Tuần Giáo, Tỉnh Điện Biên",
  },
  {
    name: "Bắc Kạn",
    code: "058",
    parent_code: "06",
    path_with_type: "Thành Phố Bắc Kạn, Tỉnh Bắc Kạn",
  },
  {
    name: "Pác Nặm",
    code: "060",
    parent_code: "06",
    path_with_type: "Huyện Pác Nặm, Tỉnh Bắc Kạn",
  },
  {
    name: "Ba Bể",
    code: "061",
    parent_code: "06",
    path_with_type: "Huyện Ba Bể, Tỉnh Bắc Kạn",
  },
  {
    name: "Ngân Sơn",
    code: "062",
    parent_code: "06",
    path_with_type: "Huyện Ngân Sơn, Tỉnh Bắc Kạn",
  },
  {
    name: "Bạch Thông",
    code: "063",
    parent_code: "06",
    path_with_type: "Huyện Bạch Thông, Tỉnh Bắc Kạn",
  },
  {
    name: "Chợ Đồn",
    code: "064",
    parent_code: "06",
    path_with_type: "Huyện Chợ Đồn, Tỉnh Bắc Kạn",
  },
  {
    name: "Chợ Mới",
    code: "065",
    parent_code: "06",
    path_with_type: "Huyện Chợ Mới, Tỉnh Bắc Kạn",
  },
  {
    name: "Na Rì",
    code: "066",
    parent_code: "06",
    path_with_type: "Huyện Na Rì, Tỉnh Bắc Kạn",
  },
];
